### ISSUE TITLE
Treemacs Perspective Not Working

### ISSUE THREAD

**Issue by chookity-pokk** [Alexander-Miller/treemacs#1013]
I am using the most recent release of both Treemacs and Perspective and the example config for `treemacs-perspective` that is given in the README, but it seems to display treemacs no differently. 

Config:

```
(use-package treemacs-perspective ;;treemacs-perspective if you use perspective.el vs. persp-mode
  :after (treemacs perspective) ;;or perspective vs. persp-mode
  :ensure t
  :config (treemacs-set-scope-type 'Perspectives))
```

**Comment by anildigital** [comment]
+1 

It doesn't work with perp-mode either 

```
(use-package treemacs-persp
  :after (treemacs persp-mode)
  :ensure t
  :config (treemacs-set-scope-type 'Perspectives))
```

**Comment by Alexander-Miller** [comment]
Looking into it.

**Comment by anildigital** [comment]
It works for me. But there are glitches sometimes in persp-mode which are fixed only when I delete persp-auto-save files and then I need to update the treemacs workspaces with treemacs-edit-workspaces.

**Comment by Alexander-Miller** [comment]
It seems to work for me as well.

There might be some confusion because switching to a _new_ perspective makes treemacs disappear because it's been visible there yet (in persp this seems to be controlled by `persp-init-frame-behaviour`), but I think this falls under working as intended, even if it's not the most intuitive.

Other than that I don't use any perspective package myself, so my means are limited. If there's something that needs to be done I need a precise and reliable reproduction recipe - from scratch: the exact config, what steps you took, what should have happened and what did happen.

**Comment by Alexander-Miller** [comment]
I'll close this issue since there doesn't seem to be any progress. Feel free to re-open if there's new information.
