### ISSUE TITLE
Modeline with doom-modeline

### ISSUE THREAD

**Issue by CaioVdmm** [Alexander-Miller/treemacs#1019]
recently i installed this package alongside with doom-modeline and doom-themes and treemacs mode line has gone and after some research and some trial and error i finally understood what is going and the cause of this error.
Its not an error, in the doom-themes-ext-treemacs.el we can see this line:
`(defun doom-themes-hide-modeline ()
  (setq mode-line-format nil))`
this line turn off the modeline.
to turn it on again i do this:
`(load "~/.emacs.d/elpa/doom-themes-20230221.610/doom-themes-ext-treemacs.el")
(defun doom-themes-hide-modeline ()
  (setq treemacs-user-mode-line-format nil))`
with this i get the file and redo de function and now i get the mode line again

sorry for some text errors, my english is basic/intermediary

**Comment by Alexander-Miller** [comment]
This is not an issue for treemacs because there is nothing I can do. Another package is using treemacs' own hooks to disable its modeline because it has decided that this is the style it wants to enforce.

You have 3 options: Use another theme, or ask the maintainer of the doom theme to make the modeline part optional, or turn it off in your own config. 

The hook is added [right here](https://github.com/doomemacs/themes/blob/e4f0b006a516a35f53df2dce2ec116876c5cd7f9/extensions/doom-themes-ext-treemacs.el#L133), so all you need to do is remove it again, like this:

```Elisp
(with-eval-after-load 'doom-themes-ext-treemacs
  (remove-hook 'treemacs-mode-hook #'doom-themes-hide-modeline))
```
