### ISSUE TITLE
Incompatibility with solaire-mode

### ISSUE THREAD

**Issue by jumper047** [Alexander-Miller/treemacs#1024]
I'm using treemacs with [solaire-mode](https://github.com/hlissner/emacs-solaire-mode). This mode makes non-file buffers background darker, so Treemacs background supposed to became darker after activating the mode. Since last update something  broken - treemacs face didn't go dark but behaved like  regular buffer. I suspect this commit - https://github.com/Alexander-Miller/treemacs/commit/26c16e997d2fa9c088042061c652ab0f6e839e2c . Internally, solaire-mode uses function `face-remap-add-relative` to remap some default faces. Seems like it clashes with the way you use faces in that commit. This behaviour can be reproduced with plain `M-x package-install solaire-mode` & `M-x solaire-global-mode`. Just compare Treemacs background with, say, background in dired buffer. They should have same color. I'm not sure how it should be fixed, so I decided just fill the issue and hope someone will find the solution:)

Just in case - to fix this issue in config, these lines should be added:
```
    (push '(treemacs-window-background-face . solaire-default-face) solaire-mode-remap-alist)
    (push '(treemacs-hl-line-face . solaire-hl-line-face) solaire-mode-remap-alist)
```

*UPD:* hooray, 1024-get:)

**Comment by Alexander-Miller** [comment]
I don't know about solaire mode, but from treemacs' PoV everything is working as expected. You now simply have 2 faces to do with as you see fit. You can change them yourself to make them look like solaire does, or you can add some spicy red on green contrast. I just need to use face remapping, which is the most straightforward and portable way to make it happen. Changing that setup because some other package *might* want to globally capture the face remapping process seems out of order to me, especially since you already have a simple solution.

So let's close this issue for treemacs and continue the conversation in solaire's repo.
