### ISSUE TITLE
treemacs-icons-catalogue some icons are black / not rendered

### ISSUE THREAD

**Issue by anildigital** [Alexander-Miller/treemacs#1042]
[Treemacs] v3.1 (installed 2023.08.04) @ Emacs 30.0.50 on macOS Ventura (13.4.1 (c) (22F770820d))

see icons are black below "src-closed"

<img width="1174" alt="CleanShot 2023-08-04 at 16 43 20@2x" src="https://github.com/Alexander-Miller/treemacs/assets/266/cd57ea16-99cd-4711-a7b3-77904dbdec7f">

**Comment by styx00** [comment]
same issue here

**Comment by VitalyAnkh** [comment]
I'm also experiencing this issue, with Emacs 30.0.50 (Development version eeda9eff1aa1 on master branch; build date 2023-08-08) on Linux.

**Comment by Alexander-Miller** [comment]
Known issue. For some reason Emacs 29+ has problems with the svg icons from https://github.com/vscode-icons/vscode-icons, but not others I have tried.

I'll close here because the issue is already being tracked in https://github.com/Alexander-Miller/treemacs/issues/1018.

If you have any other sources for good svg icons then I am all ears.

**Comment by taquangtrung** [comment]
> Known issue. For some reason Emacs 29+ has problems with the svg icons from https://github.com/vscode-icons/vscode-icons, but not others I have tried.
> 
> I'll close here because the issue is already being tracked in #1018.
> 
> If you have any other sources for good svg icons then I am all ears.

@anildigital, @Alexander-Miller: This issue happens since SVG files provided by https://github.com/vscode-icons/vscode-icons explicitly lack the 2 attributes `width` and `height` in their header. 

For example, here is the original header of: https://github.com/vscode-icons/vscode-icons/blob/master/icons/file_type_access.svg

```xml
<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" viewBox="0 0 32 32">
```

After adding `width` and `height`, it can be displayed normally by Emacs Macport in macOS: 

```xml
<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" viewBox="0 0 32 32" width="32" height="32">
```

Recently, I created a new package to display SVG icons, and fixed the above issue in this commit: https://github.com/taquangtrung/vscode-icons.el/commit/aa004508529e1fa45a5f4fd1f83c725f0f096cee

Here is my script, if you want to fix your icons: https://github.com/taquangtrung/vscode-icons.el/blob/main/scripts/fix-svg-header.py

All SVG icons after being fixed are here: https://github.com/taquangtrung/vscode-icons.el/tree/main/icons
