### ISSUE TITLE
Managing treemacs-persist file

### ISSUE THREAD

**Issue by gsilverstein** [Alexander-Miller/treemacs#1079]
Hello,

I did a bit of searching in issues and docs and could not find any information on this. Is there any way to manage the treemacs-persist file other than manually editing said file?

I had a project open in treemacs ages ago and long since removed its directory. I found I would get errors in emacs upon launching that could be bypassed but in the form of project_xyz could not be found.

I eventually found the project references in my treemacs-persist file and removed it and corrected the issue, but is there any m-x or other method to manage . clear projects here.

For reference I am using doom emacs so I'm pretty sure projectile or perspectives added this to treemacs. I don't think treemacs is doing anything wrong per-say I just want to know if there's a more optimal way to manage this.

**Comment by gsilverstein** [comment]
I actually found that this would revert but I think I've found more. Looks like the proper way to do this is edit the file through treemacs-edit-workspaces. This seems to remove the old entry in a persistent way.

**Comment by Alexander-Miller** [comment]
> Looks like the proper way to do this is edit the file through treemacs-edit-workspaces

That is the interactive all-in-one option, yes.  Editing the persist file manually will only work when treemacs is not running because it'll keep overriding it otherwise.

For single edits there are also commands like `treemacs-remove-project-from-workspace`. You can get an overview of keybinds with `treemacs-common-helpful-hydra` and `treemacs-advanced-helpful-hydra`.

`treemacs-missing-project-action` could also be relevant for you.
