### ISSUE TITLE
Add some transparency to the icons

### ISSUE THREAD

**Issue by wyuenho** [Alexander-Miller/treemacs#109]
I think one of the reasons I sometimes prefer all-the-icons is the icons are far less distracting because they blend in to the background. When I'm using a dark theme but the icons from treemacs is all bright and in my face, I get distracted so I'm tempted to turn treemacs off, but I don't want to! Treemacs is excellent! Can you consider making the icons 80% transparent or something?

**Comment by Alexander-Miller** [comment]
Sorry, but I'll have to refuse this one, for a couple of reasons:
 * Not everyone will like it and I'll get complaints to change it back
 * Multiple icon sets would swell the size of the package, and make it more difficult for me to add new ones
 * It'd open the door for people wanting different icon sets, and I want to avoid working on icons beyond the minimum needed to make them look good, because I've zero artistic talent, my icon work is usually accomplished by clicking pixels in pinta and hoping it'll look ok
 * I don't even know how to do that. I assume some imagemagick script could do it, but my attempts have been unsuccessful so far. If it is possible with a simple shell script you could easily do it yourself.

I have recently completed an overhaul of the icon system, it is now fully customizable. The non-graphical terminal look can also be enabled in the gui version. You can look it all up under Custom Icons in the readme. I'll also add a section about how to more or less use all the icons. The short version is you use the following script and patch up stragglers with `treemacs-define-custom-icon`.

```
(with-eval-after-load 'treemacs
  (dolist (item all-the-icons-icon-alist)
    (-let [(ext func . args) item]
      (puthash (s-replace-all
                '(("\\" . "")
                  ("^" . "")
                  ("$" . "")
                  ("." . "")
                  ("?" . "")
                  ("*" . ""))
                ext)
               (concat (apply func args) "\t")
               treemacs-icons-hash))))
```
