### ISSUE TITLE
Treemacs opens with `(wrong-type-argument arrayp nil)`

### ISSUE THREAD

**Issue by gopar** [Alexander-Miller/treemacs#1101]
When I try to open treemacs, I get the following trace:

```
Debugger entered--Lisp error: (wrong-type-argument arrayp nil)
  (treemacs-project->refresh! #s(treemacs-project :name ".emacs.d" :path "/Users/gopar/.emacs.d" :path-status local-readable :is-disabled? nil))
  (mapc treemacs-project->refresh! (#s(treemacs-project :name ".emacs.d" :path "/Users/gopar/.emacs.d" :path-status local-readable :is-disabled? nil)))
  (-each (#s(treemacs-project :name ".emacs.d" :path "/Users/gopar/.emacs.d" :path-status local-readable :is-disabled? nil)) treemacs-project->refresh!)
  (treemacs--do-refresh #<buffer  *Treemacs-Scoped-Buffer-#<frame /Users/gopar/caryak/user-service/ 0x15c8eca30>*> all)
  (treemacs-hide-gitignored-files-mode)
  (run-hooks change-major-mode-after-body-hook special-mode-hook treemacs-mode-hook)
  (apply run-hooks (change-major-mode-after-body-hook special-mode-hook treemacs-mode-hook))
  (run-mode-hooks treemacs-mode-hook)
  (#f(compiled-function () (interactive nil) #<bytecode 0x382179d3301314>))
  (apply #f(compiled-function () (interactive nil) #<bytecode 0x382179d3301314>) nil)
  (treemacs--mode-check-advice #f(compiled-function () (interactive nil) #<bytecode 0x382179d3301314>))
  (apply treemacs--mode-check-advice #f(compiled-function () (interactive nil) #<bytecode 0x382179d3301314>) nil)
  (treemacs-mode)
  (treemacs--init)
  (treemacs nil)
  (funcall-interactively treemacs nil)
  (call-interactively treemacs nil nil)
  (command-execute treemacs)
```

Not sure what the issue can be. Was working fine a few weeks ago (Don't use this feature a lot so it could of broken a while ago and I just only realized it now).

Apprecaite the help!

**Comment by Alexander-Miller** [comment]
> (wrong-type-argument arrayp nil)

An error like this means there is something borked in treemacs' internal state. Finding that something however is difficult because treemacs has its own kind of dom implementation that mirrors what you see on screen, meaning its state is both very dynamic and can be very large.

So let's try the basics first. Update treemacs and make sure you restart Emacs after you do. Reset your workspace (you can backup your `treemacs-persist-file` and make quick edits with `treemacs-edit-workspaces`). Does the error still happen? For any content in your workspace or only for you emacs.d project?

**Comment by gopar** [comment]
Hey Thanks! I had uninstalled/re-installed and restarted emacs before posting. But it looks like deleting `treemacs-persist-file` did the trick (along with the re-installing and restarting).

Closing ticket. Thanks again!
