### ISSUE TITLE
Line up files to the same column of the start of directories

### ISSUE THREAD

**Issue by wyuenho** [Alexander-Miller/treemacs#111]
<img width="187" alt="screen shot 2017-11-23 at 23 59 22" src="https://user-images.githubusercontent.com/160028/33190901-684ed21c-d0aa-11e7-8256-404fbe5d0f6d.png">

In TUI mode, the flat files line up to the first column along with the +, this is at odds with pretty much every other text based directory hierarchy display. Flat files should be indented 2 columns.

**Comment by Alexander-Miller** [comment]
> this is at odds with pretty much every other text based directory hierarchy display

Except for neotree. I did try to make the alignment look different at the start, but that's the only way I could make it work then. The code got simplified since, so I can make the requested change.
https://github.com/Alexander-Miller/treemacs/commit/c43ac4efb06d115ff62621b90c218cdbdc39d0f5 adds a simple unicode text icon as tui fallback.
See the addition to the readme if you want a different file icon.
