### ISSUE TITLE
[Feature Request] Three-panel view instead of two-panel view

### ISSUE THREAD

**Issue by phyliu79** [Alexander-Miller/treemacs#114]
It's nice that the file structures ( Top  two level sections) are also shown by treemacs. However, it is not very convenient to show them within the directory panel - Especially when edit a file with a big structures (For example a org file).

If it is easy, would you mind to design a three-panel view by the following way?
Left panel: directory of files
middle panel: list structures of one file - (Can be a little wider). 
right panel:  a **narrow view** (by default) to the current file. When click any title of subtree from the middle panel, the right panel show only the contents of the corresponding subtree. (For narrow view to the subtree, the org function _org-narrow-to-subtree_ may help)

**Comment by phyliu79** [comment]
The file structure column can be added by other packages. For example, imenu-list

**Comment by Alexander-Miller** [comment]
Yes, imenu-list can definitely more readily offer what you want. helm-semantic-or-imenu is also a good candidate if you want fuzzy matching.

I would've rejected this issue myself as well, on the grounds that it does not fit in with the general concept of treemacs as a single side window, but especially because implementing something like this as part of treemacs would be extremely difficult and terribly fragile.
