### ISSUE TITLE
Any way to change the default directory when starting treemacs?

### ISSUE THREAD

**Issue by xli1224** [Alexander-Miller/treemacs#120]
I'm using spacemacs and having treemacs layer added. It's working awesome!

However, there is one thing that I couldn't find an answer. I am using emacs just for writing org notes. I have all my notes in one folder so every time I open emacs and I open treemacs window, I would like to see it's locating my note folder as the root, but it seems it's using the home folder as the default choice.

Is there any way to set a customize folder for treemacs so that it will locate that directory as the root folder at startup? So far I only found that turn on the persist states might be an option but not very useful sometime as I also would navigate into different folders in treemacs.

**Comment by Alexander-Miller** [comment]
Using a prefix argument takes you close and I'll make a note to mention it in the readme.
Quite a few functions a treemacs behave slightly different when you call them with `C-u`.  For `treemacs` & `treemacs-projectile` that means letting you select the directory/project that should serve as the root dir.
If you want a single keypress solution you can call `treemacs--init`, which builds treemacs with the dir you give it. 
Note that I'll probably change its name to `treemacs-init` in a future version, since it can well be used by other packages.

**Comment by enphysoft** [comment]
I started using treemacs, which I like a lot. 
I also got the same problem regarding the default directory, which I cannot change.
It is written in a file ~/.emacs.d/.cache/treemacs-persist. I assigned my $HOME directory as a default.
