### ISSUE TITLE
Treemacs messes with org-capture behaviour.. opens additional frame but focus is not on it.

### ISSUE THREAD

**Issue by anildigital** [Alexander-Miller/treemacs#121]
I noticed when treemacs sidebar is opened..  and I press C-c c (i.e. (org-capture &optional GOTO KEYS)

It does following things wrong.

1. It opens another frame (I don't expect a new frame for org-capture.. just current file frame)
2. Okay, if I accept that treemacs need another frame, but I expect focus goes on on new frame for the org-capture thing. but it focuses on the wrong frame, I had to change to proper window/frame for this

**Comment by Alexander-Miller** [comment]
The good news is: I know exactly what you mean.
The bad news is: there is nothing I can do about it.

The problem is that the treemacs window is dedicated to showing the treemacs buffer. This is strictly necessary and prevents emacs and packages from displaying buffers other than treemacs in the side window. Without this setting you'd have problems like emacs using the treemacs window to show you a stack trace. 
For whatever reason the presence of a dedicated window (it is not specific to treemacs)  makes org spawn another frame. This is done because org calls `org-no-popups`, which disables all the usual  buffer spawn settings. So what you are seeing is plain vanilla behaviour, enforced by org-mode.

I am not going to change org-mode's default behaviour, I cannot be sure of the effects this might have elsewhere. What I can offer you is a workaround, one I use myself. I've the following code in my config:

```
(with-eval-after-load 'org
    (defun org-switch-to-buffer-other-window (&rest args)
      "Same as the original, but lacking the wrapping call to `org-no-popups'"
      (apply 'switch-to-buffer-other-window args)))
```

This will change org's window spawning behaviour to be again controlled by `display-buffer-alist`, so you can use a package like shackle or popwin to tell org what to do.

As far as I'm concerned the issue you're having is a bug in org-mode. It should not open a new frame in the presence of a dedicated window and should definitely not misplace the focused window. You should report this as an emacs bug.

**Comment by anildigital** [comment]
Thanks for info! 👍🏼 
I am using that code now.
