### ISSUE TITLE
Follow mode not work

### ISSUE THREAD

**Issue by LuhengStat** [Alexander-Miller/treemacs#140]
I've just installed treemacs, and I found the follow mode not work: I open one file and after i change into another file, the tree not update. Does there exists something wrong of my operation. Besides, 
The follow mode and the watch mode is enabled.

**Comment by Alexander-Miller** [comment]
* Is the other file you are moving to inside the root directory that treemacs is showing?
 * What happens if you call `treemacs-find-file`?

**Comment by LuhengStat** [comment]
Yes, I am changing the root directory. And If i call treemacs-find-file, the directory will change. 
I am wondering does there a way that the directory will auto change no matter the file is inside the 
root or not? Thanks.

**Comment by Alexander-Miller** [comment]
Do I understand you right, you are jumping to a file that's *outside* the treemacs root directory? So for exmaple if treemacs is showing files in `~/Documents/Stuff` you jump to `~/Documents/foo-file`.

> I am wondering does there a way that the directory will auto change no matter the file is inside the
root or not? Thanks.

No, and it is not a change I will be making. Right now the change would be simple, however in the future I plan to make it possible to show multiple roots at once. The less I need to worry about two roots showing the same files, the easier - and therefore faster - that feature's implementation will be. Arbitrary jumping upwards in the file system meanwhile goes in the opposite direction.

If you're working on two different project you can 1) select a root that includes both, or 2) use multiple emacs frames, since every frame will have will have its own unique treemacs buffer.

**Comment by LuhengStat** [comment]
Thanks. I understand that. I think you are right and in most cases we are working in one root directory. Best
