### ISSUE TITLE
Priovide the option to automatically create files in the current directory

### ISSUE THREAD

**Issue by YourFin** [Alexander-Miller/treemacs#144]
I just downloaded treemacs today, and so far it's awesome. However I must admit I got rather confused on attempting to create a file or directory, as when I put in the name of the file I wanted to create in the first box that appeared (this may have something to do with helm), Treemacs got pissy with me about this not being a directory. 

The behaviour I expected, as a naïve user, was that the file/directory would be created in the same level as my cursor. For example, if the parent folder was ~/gitproj/foo, and my cursor was over ~/gitproj/foo/bar or ~/gitproj/foo/potato.sh that I would be prompted to create a new file/dir in ~/gitproj/foo automatically, as opposed to having to specify this. 

I propose, then, that this be offered as an (default?) option to users like me. It should be fairly simple, I think it could be accomplished with replacing the 

          (setq location (read-directory-name "Create in: " curr-path))

with 

          (setq location (if treemacs-ask-creation-dir (read-directory-name "Create in: " curr-path) curr-path))

in the definition of `treemacs--create-file/dir`

Does this make sense? If so I'd be happy to put in a PR.

**Comment by Alexander-Miller** [comment]
The current approach is more or less a workaround for the sake of simplicity. Ideally I'd handle file creation as you propose (and `helm-find-files` does) - by letting you type the full name and creating every directory in between. I went for the current version because it's a lot easier than to check and maybe create every dir in the /a/b/c/d/e/f/g/h line a user has entered.

A PR would be much appreciated. You don't even need to leave an option for the current behaviour, properly handling user input is the better approach. Just one final thing: the PR should go against the [shadow-tree branch](https://github.com/Alexander-Miller/treemacs/tree/shadow-tree). I've done some heavy refactoring for #143, and the file creation logic (but no its behaviour) is also affected. I'm mostly cleaning up now, so it should be merged into master soon enough.

Looking at the code I'm also not sure what that first `if (null btn)` is doing. It's probably a bug.

**Comment by Alexander-Miller** [comment]
#143 is now in master, so you don't have to track other branches anymore.
