### ISSUE TITLE
icon background color?

### ISSUE THREAD

**Issue by avkoval** [Alexander-Miller/treemacs#148]
Hi,
Thank you Alexander for a great product, specifically for the feature to have multiple trees possible - that was the last most important thing I missed in this product.

I have very small question/bug report: sometimes, when I open treemacs it won't display dark icon background color. After theme on/off it starts doing it:

Initial state on first call:

![](http://scr.ua2web.com/avk/ss_20180210085758_vVa0WOwsdV5HBOeSwQj2.png)

After theme on/off

![](http://scr.ua2web.com/avk/ss_20180210085847_lpp2DIc1Qx9V5iwElgwn.png)

That apply for all themes, not just this one. After switching theme on/off once things became sorted out and it works well afterwards for all other instances of treemacs in different folders.

Any hint/ideas whats wrong?

**Comment by Alexander-Miller** [comment]
Png images in emacs have a static background color by default, even when hl-line-mode is on them, as in treemacs. To avoid this I do some manual background color setting. To do that treemacs of course needs to know which colors to use - information it gets from your theme (and changes when you load a different theme). There's some more info about this in the FAQ in the readme.

It looks like on first loading your theme's default background color is not properly defined somehow. It's double odd that's it's working when you reload your theme. Let's dig into this a little:

 * Check your logs on start, after loading treemacs. Do you see any warnings?

 * How is your loading process? Is treemacs correctly loaded *after* your theme? Treemacs is a fairly large package, it should definitely be lazy-loaded,

 * What is the output of `(face-attribute 'default :background nil t)` both before and after you reload your theme?

**Comment by avkoval** [comment]
OK, with the help of your advices I've been able to fix it. At first, I've tried with emacs -Q and your package alone - the problem was not reproduced. Digging into config file revealed that commenting this line:

```
;;  (require 'treemacs)
```

Fixed the problem. package.el already loads treemacs and so this additional require was not needed. After I commented this link everything became sane.

Thank you Alexander!

**Comment by mpanarin** [comment]
Sorry to dig up this issue, but I have the same problem.

Emacs 26.1 (Spacemacs on develop branch)
exactly same behaviour as described by OP. 

1. No warnings in \*Messages\* buffer 
2. Don't have require on treemacs, only thing I have is:
```
  (with-eval-after-load 'treemacs
    ;; treemacs set simple git mode
    (treemacs--setup-git-mode 'simple)
    (treemacs-toggle-show-dotfiles)
    (add-to-list 'treemacs-ignored-file-predicates
                 (lambda (filename filepath)
                   (string-match-p "\.pyc$" filename)))
    ;; fix treemacs horizontal/vertical ace
    (define-key treemacs-mode-map (kbd "o a h") 'treemacs-visit-node-ace-vertical-split)
    (define-key treemacs-mode-map (kbd "o a v") 'treemacs-visit-node-ace-horizontal-split)
  )
```
and removing this doesn't help.
3. `(face-attribute 'default :background nil t)` returns the same value before and after theme reload
"#002b36" (Solarized-dark)

**Comment by Alexander-Miller** [comment]
Since I don't know what's going on there's not much I can do on my end. So you can either use a simple workaround or keep digging.

For the workaround it should be enough to set `treemacs--selected-icon-background` and `treemacs--not-selected-icon-background` to the right colors (might have to do it *before* treemacs loads). 

And if you want to keep digging you should start with the place where these variables are defined in treemacs-visuals.el and step through that code and see if there's anything suspicious in there.

**Comment by DougBeney** [comment]
Very strange bug. I have two machines running Emacs 26.1 and use the same configs. Both are Linux, one is Fedora and the other is Solus.
With Fedora, I never experience this problem. On Solus, I do experience this problem.

One thing I have noticed is that if you go into `customize-themes` and hit the save button the problem is solved...temporarily until you close and open Emacs again.

**The Solution:**

I found out that you could create a treemacs-mode hook to reload your theme when Treemacs loads for the first time. Works perfectly for me.

`(add-hook 'treemacs-mode-hook (lambda () (load-theme 'sanityinc-tomorrow-blue t)))`

Replace `sanityinc-tomorrow-blue` with the name of your theme.

**Comment by PanarinM** [comment]
@DougBeney for me the problem went away after some system upgrade not so long ago (Manjaro Linux). So, probably, it's emacs/distro related

**Comment by Alexander-Miller** [comment]
@DougBeney 

Loading the theme is quite heavy. Does it help if you put `treemacs--setup-icon-background-colors` into the hook instead?

**Comment by DougBeney** [comment]
@Alexander-Miller Worked perfectly!

**Comment by Alexander-Miller** [comment]
Great, I've included it with the setup code of treemacs' major mode, so you shouldn't need workarounds anymore if your treemacs is up to date.

**Comment by DougBeney** [comment]
Nice work! Seems to be fine. Issue could probably be closed if nobody else is having problems.

**Comment by DougBeney** [comment]
Ok, so I noticed that this problem still occurs in the atom-one-dark-theme. Other themes I have tried worked fine.
