### ISSUE TITLE
Error running timer ‘treemacs--process-file-events’: (wrong-type-argument treemacs-shadow-node nil)

### ISSUE THREAD

**Issue by technician77** [Alexander-Miller/treemacs#168]
I seem to get this error after some time. What is more strange is that I get the error even though the treemacs window is not open.

**Comment by Alexander-Miller** [comment]
>  get the error even though the treemacs window is not open.

That part is normal. Filewatch-mode runs its refresh no matter if treemacs is visible or not.

Getting to the cause of the error is however quite a bit tricky, since errors on a timer leave no stacktrace and the problem is highly dependant on your treemacs state. Long explanation short: I call it the shadow tree because it's the file structure shadowing the visible file tree and that error means some entry is missing that supposedly should be in there.

We can try the following: You evaluate the following function:

```
(defsubst treemacs-get-from-shadow-index (key)
  "Get node with KEY, if any."
  (--if-let (ht-get treemacs-shadow-index key)
      it
    (treemacs-log "Node for key [%s] missing in shadow index" key)))
```

Then you wait for the error to occur and then report back when it happened and what your file tree, epsecially the node with the missing entry, looked like.

Most likely I'm just missing a null check somewhere, but the fact that it happens means I made a wrong assumption somewhere, so I'd like to get to the bottom of this.

**Comment by Alexander-Miller** [comment]
Does the issue persist with the newest treemacs version?

**Comment by technician77** [comment]
No, disappeared.
