### ISSUE TITLE
[Feature] Treemacs as file/directory selector

### ISSUE THREAD

**Issue by yyoncho** [Alexander-Miller/treemacs#184]
treemacs poping into a separate frame(window?) could act as a replacement for read-file-name-function and it will be great fit for evil users since it will provide evil-mode navigation(ido-find-file/helm-find-files do not provide such).

**Comment by Alexander-Miller** [comment]
It would also mean no fuzzy matching and TAB completion, making it a bad drop-in replacement.

Technically I could make this work, but it would require a nontrivial amount of bending things into the right shape and I'm not sure if it is worth the effort. Do you have a concrete use-case in mind?

**Comment by yyoncho** [comment]
I believe that there is no need for fuzzy match/tab completion since "/" is already available. If you want to create new folder/file you have "c d" and "c f", etc. so all the navigation is already in place. My idea is just to open treemacs in new frame(window?) with "ENTER" key action replaced with (close frame) (return selected item path). Here it is the equivalent dialog in windows http://www.ammara.com/access_image_faq/images/browse_for_folder.gif . 

I am not 100% convinced that it will be better than helm/ido selectors and that I will keep it as my default file selector but I would give it a try. 

I guess https://github.com/Alexander-Miller/treemacs/issues/176 is a blocker. If you disagree with the "usefulness" of such feature you could assign it to me and I will implement it.

**Comment by Alexander-Miller** [comment]
>  If you disagree with the "usefulness" of such feature  you could assign it to me and I will implement it.

It's not that I explicitly disagree, it's that I see think it's likely that despite being an interesting nice-to-have it'll go unused without some specific use-case or intended audience since you need to make the explicit decision to use a graphical treemacs instead of the usual input. That decision must be motivated by *something*, just offering the feature and advertising it in my readme is probably not enough.

Now you did kindly volunteer to use and implement it both, so you're welcome to have a go at it. I don't think #176 is necessarily a blocker, the selection dialog is short-lived and independent from the other treemacs buffers, so it shouldn't be a problem, unless ad-hoc navigation is a feature you explicitly want. It should be easy enough to add it later anyway.

Couple thoughts on the feature from my side:
 * There's a small chapter about Contributing in the readme that explains the basics, mostly the usual things, plus the makefile.
 * Changes are big and separate enough to warrant another module.
 * You'll need to gut the keymap. Most of the usual features should not be available.
 * Doesn't make sense to be able to open tags either.
 * Same goes for the minor modes. Vars like `treemacs--git-status-process/parse-function` and `treemacs--ready-to-follow` should be locally set to #'ignore/nil.
 * Don't know if you can directly use the top-level initializers to render the dialog, but they mostly delegate to more primitive functions that just insert the things text in the current buffer.
 * There should probably be two functions offered as api: one that exposes all the details, (like whether to spawn in a frame or window, the size and position of the frame/window, which dir to use as root, what to preselect etc), and a dwim variant to use as a read-directory-function replacement. Maybe the exact behaviour can be controlled with `defcustoms`.

**Comment by yyoncho** [comment]
I am closing this since I found a replacement for that tool, available in `spacemacs`.When you are in `helm` buffer you can press `M-spc` which will start `hjkl` navigation which would cover what I have described in this ticket(my pain point). Feel free to reopen if you still want to reimplement it, sorry for bothering you.
