### ISSUE TITLE
Some of the key bindings are offputting.

### ISSUE THREAD

**Issue by LeviHarman** [Alexander-Miller/treemacs#194]
There are too many default keybindings some of the dangerous. Delete with d and confirm with y would result in deleting recursively any directory under the cursor if you accidentally type Randy, Dandy or plenty of other words that end in dy. 

I think you should rebind p to Treemacs-add-project rather than move line up? And leave C-p to move up one line, and C-n to move down one line. I think that better fits in with emacs defaults. 

I think you should consider putting some of the keybindings in menu prompts by default, like how you prompt for deletion with the 'y' key after hitting 'd'.

**Comment by Alexander-Miller** [comment]
> if you accidentally type Randy, Dandy or plenty of other words that end in dy.

Not sure whyever you would want to type that, but I suppose it's a good idea to want an explicit "yes" instead. 

> I think you should rebind p to Treemacs-add-project rather than move line up? 

Line movement is used much more often than project interactions, so it should be the simpler keybind. Maybe it doesn't quite fit with the defaults, however 1) Emacs' defaults aren't very good in the first place and everyone customizes them anyway, and 2) keybindings are not supposed to please everyone, because they won't. Luckily they are easy to change.

**Comment by yyoncho** [comment]
I agree with @Alexander-Miller. I have few proposals:
1. Add option 'delete by moving to trash'
2. Make confirmation function configurable (the default might be 'yes-or-no-p' or 'y-or-n-p')

**Comment by yyoncho** [comment]
Also, I am not sure whether it is doable but undo delete(when file moved to trash) functionality will be great.

**Comment by Alexander-Miller** [comment]
> Add option 'delete by moving to trash'

Good idea. Should in fact be the standard, judging by `delete-by-moving-to-trash` being t for me.  Irreversible delete can still be accessed with a prefix arg.

> Make confirmation function configurable

Default should be yes-or-no since we're dealing with deleting files.

> Also, I am not sure whether it is doable but undo delete

Unfortunately not. It doesn't look like emacs knows how to recover files from the trash.

**Comment by yyoncho** [comment]
I hoped that you might find a solution. As a side note there is a package `trash-cli` (https://github.com/andreafrancia/trash-cli available on debian based distros) which could be used for implementing delete/restore on linux.

**Comment by Alexander-Miller** [comment]
The solution would be to do everything manually - implement undelete for Windows and Mac and a dozen Linux DEs. The cost-value ratio for such an undertaking is terrible (at least from a treemacs POV) and it's far outside the scope of something like treemacs anyway. It's the kind of feature that deserves its own package or should even be integrated into core emacs if possible.

**Comment by LeviHarman** [comment]
Hello Alexander-Miller. Thanks for taking the time to let me know what you think. I see your point about line movement. d-y being turned to d-'yes' sounds good too.

**Comment by Alexander-Miller** [comment]
Pushed the discussed changes now.

 * Moving to trash is now the default option.
 * Total deletion is available with a prefix arg.
 * Confirmation works with `yes-or-no-p`. Some people change its function pointer to `y-or-n-p`, but there is nothing I can do in that case - `yes-or-no-p` is implemented in C so I cannot even copy the code.
