### ISSUE TITLE
Reordering Projects

### ISSUE THREAD

**Issue by inspell** [Alexander-Miller/treemacs#199]
Is there a way to reorder my projects once added?
Sorry if the feature is there and I missed it. I am not very familiar with treemacs - I just started using it.

**Comment by Alexander-Miller** [comment]
Not yet, but it's on the todo list.  Ad-hoc navigation comes first, what with so many people asking for it.

**Comment by Alexander-Miller** [comment]
Small update, since this is taking a while: instead of going for the straightforward solution I've decided to begin implementing a wider reaching feature. 

Right now the way treemacs saves its workspace state is by simply dumping its internal objects' string representation on your hard drive. It's super simple, but that's where the utility stops. I have long planned to replace that with a format that's both human-readable and human-editable. 

Once that is in place I can use that format to also let users edit the details their workspace configuration, including the order of their projects. It's not quite the same as calling something like `treemacs-project-move-up` until everything's in place, but letting you edit everything at once with whatever text editing features you're used to is also an advantage.

As for the exact format I need something easy to produce and parse, so (unless someone has a better idea) I will go conf files and your workspace will look like this in the future:

```
[Workspace]
name=Default Workspace

[[Project]]
name=Treemacs
path=/home/a/Documents/git/treemacs

[[Project]]
name=Org
path=/home/a/Documents/Org

[[Project]]
name=Dotts
path=/home/a/Documents/git/dotfiles

[[Project]]
name=pfuture
path=/home/a/Documents/git/pfuture

[Workspace]
name=Test

[[Project]]
name=Foo
path=/home/a/Documents

```

**Comment by Compro-Prasad** [comment]
`M-up` and `M-down` like in org mode should be preferable way to reorder projects/workspaces.

**Comment by Alexander-Miller** [comment]
I haven't forgotten about this issue, just got side-tracked for the last 200 or so commits.
Luckily I've found out about `transpose-regions` which made project moving a lot easier to accomplish, so (permanently) moving projects with M-up/down is in now.

**Comment by dmocek** [comment]
Just found this feature through this issue...awesome...thanks!
