### ISSUE TITLE
Using similar bindings to evil-magit?

### ISSUE THREAD

**Issue by jojojames** [Alexander-Miller/treemacs#20]
What do you think about using some bindings from evil-magit?

https://github.com/emacs-evil/evil-magit/blob/master/evil-magit.el

Some decent ones, [ and ] to move up and down siblings (I think treemacs is using C-j and C-k for that right now). and gr for refresh so g and GG (and the other g as prefix binds) can be used.

**Comment by Alexander-Miller** [comment]
If there's one thing treemacs taught me about keybinds it's that I'll never have a keymap that works for everyone. I'll add the gr bind for evil because that is a genuine bug - refresh on g is something others have asked me for and I forgot to take evil's use of g into account.

Adding anything that does not fit the spacemacsy mnemonic pattern used so far, especially changing long established defaults is an absolute no-go.

Changing that stuff yourself is trivial and the readme contains a comprehensive and up-to-update list of all the features you can use (and if it doesn't let me know).

**Comment by jojojames** [comment]
Sounds good, I was hopeful there'd be a strong set of defaults on the evil package and any tweaks to those defaults the user can do themselves.

**Comment by Alexander-Miller** [comment]
https://github.com/Alexander-Miller/treemacs/commit/423fd3029006fdeaa972338a7dfb0a591100e6ce
