### ISSUE TITLE
Have "RET" behave like mouse click?

### ISSUE THREAD

**Issue by jojojames** [Alexander-Miller/treemacs#21]
I'm using

```
    (evil-define-key 'treemacs treemacs-mode-map (kbd "RET") 'push-button)
    (evil-define-key 'treemacs treemacs-mode-map [return] 'push-button)
```

to get the "RET" to map to push-button.

1. What do you think about setting that as a default (or configurable)? As of now, pressing RET on a directory doesn't do anything.

1.a. Looks like with the recent change, push-button can be bound to RET but unnesting and renested directories don't work because the cursor can hop out of range of the button after pressing RET.

EDIT:
;; Looks like this is fixed already.
_2. It looks like we're using
```
  (treemacs--evade-image)
```

so even if RET was mapped to push-button, the cursor isn't actually on the button._

**Comment by Alexander-Miller** [comment]
> What do you think about setting that as a default (or configurable)? As of now, pressing RET on a directory doesn't do anything.

I don't quite like the idea of RET just repeating TAB, seems like a waste of an improtant key to me. But at least it's better than inconsistenly working only on files.

> so even if RET was mapped to push-button, the cursor isn't actually on the button.

It should be `treemacs-push-button`. That'll make sure you hit the right button.

Note since you're talking about mouse clicks: the current mouse interface is due for a change, clicks are supposed to only do anything when clicking the icons for now, but I mistakenly used the wrong function. Clicking on text is reserved in case I find a better use for it later,

**Comment by jojojames** [comment]
Thanks, I'll be watching for any updates.

**Comment by Alexander-Miller** [comment]
https://github.com/Alexander-Miller/treemacs/commit/2a8d22559141daa3feaad30c466eaecc83c9dad5
