### ISSUE TITLE
Question: Emacs version

### ISSUE THREAD

**Issue by seagle0128** [Alexander-Miller/treemacs#216]
I noticed from 2.1.1, `treemacs` needs `Emacs 25.3+`, while before just needs `24.4+`. 
Could you please explain why update the dependency of it?
If I have to use Emacs 24.4, how to use `treemacs` with MEPLA packages?
Thanks,

**Comment by seagle0128** [comment]
I found this issue https://github.com/Alexander-Miller/treemacs/issues/208.
Closing it.

**Comment by seagle0128** [comment]
Just curios, why not 25.1+, should be 25.3+?

**Comment by Alexander-Miller** [comment]
There are a couple of reasons.

 * Emacs 26 is plain obsolete, it was released 6 (or 3 years ago, depending on how you look at it)
 * I have no wish to maintain compatibility for an obsolete Emacs version, that last I tried I couldn't even compile.
 * That means missing out on features that I do use, or plan to use like generators, threads, dynamic modules and xref.
 * There's also the trouble of oftentimes running into simple utility functions like alist-get that have only been around since Emacs 25.
 * There's also some syntactical differences, like that annoying handling of pcase.
 * Plus some more issues that I cannot even remember that made me disable the Emacs 24 CI build.

> Just curios, why not 25.1+, should be 25.3+?

I see no reason to pick an older Emacs 25. 25.3 was the most up-to-date version until 26 came along, and I'll support it at least until the release of Emacs 27.

> If I have to use Emacs 24.4, how to use treemacs with MEPLA packages?

I don't know. With the fix from the issue you link you probably just won't be able to upgrade you version.
Whatever is forcing you to stick with Emacs 24, I hope it's not permanent.

**Comment by seagle0128** [comment]
Thanks for the detailed explanations, @Alexander-Miller !
I've upgrade to Emacs 26.1 in my envs. I also decide to not support Emacs 24. The only concern is Emacs 25.2 is packaged with Ubuntu 18.04 LTS. For some remote development machines, I have to keep them in 25.2.

**Comment by Alexander-Miller** [comment]
Ah, I hadn't considered that some of the more stable distros would ship with older Emacs25 version, I thought 25.3 would be the standard outside of maybe over-conservative corporate networks.

That is a good reason to dial back the min version.

**Comment by Compro-Prasad** [comment]
@Alexander-Miller First point in https://github.com/Alexander-Miller/treemacs/issues/216#issuecomment-397762098 is probably incorrect about the version.

**Comment by Alexander-Miller** [comment]
Yes, I meant Emacs 24.

**Comment by seagle0128** [comment]
Cool! Thanks very much!
