### ISSUE TITLE
Treemacs Evil: Hide Cursor.

### ISSUE THREAD

**Issue by rnaby** [Alexander-Miller/treemacs#235]
Is there any way to hide the cursor in the **Treemacs** buffer while in **Evil** mode?

**Comment by Alexander-Miller** [comment]
That depends. If you're in a GUI then that's the default behaviour. If you're in a TUI then no, the cursor - and that applies for all of emacs - is controlled by the terminal.

**Comment by rnaby** [comment]
But at GUI when the Evil mode isn't active there were no cursor... The cursor was only at the buffers which has code then. Now in Evil mode it's everywhere. Is there any way to make the cursor available to the code only buffers? Or this issue is actually related to Evil mode package ?

**Comment by Alexander-Miller** [comment]
Are you sure you don't mistake the fringe bitmap, introduced by `treemacs-fringe-indicator-mode`, for a cursor? Because that's just there to help you see where you are.

One of the reasons treemacs-evil exists is to make sure that the cursor stays hidden with evil-mode. Make sure it is loaded: does `(featurep 'treemacs-evil)` return `t`?

**Comment by Compro-Prasad** [comment]
@rnaby ^^

**Comment by rnaby** [comment]
Actually, currently I've moved from treemacs to dired again. So this issue is no more need to continue. Anyway, thanks for your support though. :+1:
