### ISSUE TITLE
Use `P` instead of `C-p` for project prefix

### ISSUE THREAD

**Issue by Compro-Prasad** [Alexander-Miller/treemacs#246]

**Comment by Alexander-Miller** [comment]
Sorry, but nope.

 * P is already taken for peeking.
 * I'd be breaking backwards compatibility and probably annoy a bunch of other people.
 * The last time I tried to make every happy with my keymaps I ended up with 3 different ways to refresh treemacs.
 * Which is why I've given up on it.
 * The change you want is just a single `define-key` call away, so it's not like you are forced to use treemacs in a way you don't like.
