### ISSUE TITLE
Allow nested directories as a new project root

### ISSUE THREAD

**Issue by ogdenwebb** [Alexander-Miller/treemacs#265]
It's related to adding a new project into workscape.

For example I have the following directories.
```
~/dotfiles/
~/dotfiles/emacs
```

So I want to add both of these directories as different treemacs projects, but treemacs doesn't add `~/dotfiles/emacs` after `~/dotfiles`, because `a project already exists`. Also it seems a bit odd, because treemacs allows you to add a nested directory before a parent.

**Comment by Alexander-Miller** [comment]
> Also it seems a bit odd, because treemacs allows you to add a nested directory before a parent.

That's because it's a bug. Both ways should be blocked.

I'll have to decline this. Not because I want to - I don't - but because allowing a path to appear more than once in treemacs means throwing correctness out the window. Long story short when an absolute path is not a unique key selecting and updating files won't work properly. There's a more thorough explanation in https://github.com/Alexander-Miller/treemacs/issues/176.

I might come back to this some day, but for now I've plenty other things to do, so I'm afraid you'll have to live with this inconvenient limitation.
