### ISSUE TITLE
Icon improvements

### ISSUE THREAD

**Issue by benwtks** [Alexander-Miller/treemacs#289]
Is there or please can someone add a way to make the icons more subtle? Like monochromatic? Something like atom's file icons? Currently the icons are really distracting (might even be a deal breaker)

**Comment by Alexander-Miller** [comment]
Not really, but there's a couple things you can do: Set `treemacs-no-png-images` to t, you can head over to #287 and ask @yyoncho if he'd want to include something like that or I can do it when the infrastructure's there, or you can change the icons yourself, [it looks quite doable with imagemagick](https://www.imagemagick.org/discourse-server/viewtopic.php?t=11279).

**Comment by yyoncho** [comment]
I think that we can have Atom theme :)

**Comment by benwtks** [comment]
Yeah octicons would be great!

**Comment by seagle0128** [comment]
Is there any possible to support https://github.com/jojojames/vscode-icon-emacs?

**Comment by Alexander-Miller** [comment]
Yes, but I won't do it.

1) I am using my own format for icons (a specifically formatted string with quite a bit of meta-data) that would need translation. 
2) That bit of overhead alone would be reason enough, but as far I can see that package is running quite a lot of code - string concatting and file-exists checking - for every single icon, code that would go straight into the heart of my most performance critical code. And did I ever tell you how paranoid I am about performance?

Now when I say I won't do it I mean I won't use the package directly, but I will make use of the actual icons, you did cast your vote in that ticket. I'll be adding more icons gradually, but right you can see on the issue tracker that my plate is all sorts of full, so that is what I'm doing now.

**Comment by seagle0128** [comment]
Thanks, @Alexander-Miller. 

It's fine not to use the package directly, I think. You can improve the current icons according to `vscode-icons`. That's great!

BTW, I am using `all-the-icons` in treemacs, and it looks great for me.

![image](https://user-images.githubusercontent.com/140797/47224950-66320a00-d3ef-11e8-9bec-2c8ec7c33f3f.png)

**Comment by itome** [comment]
@seagle0128 Looks great, can you share your config file about treemacs and all-the-icons?
It may be good option for treemacs appearance.

**Comment by seagle0128** [comment]
@itome I am using `doom-themes` and use this configuration. 
NOTE: `M-x all-the-icons-install-fonts` to install fonts.

```elisp
(use-package doom-themes
    :init (load-theme 'doom-one t)
    :config
    ;; Enable flashing mode-line on errors
    (doom-themes-visual-bell-config)

    ;; Corrects (and improves) org-mode's native fontification.
    (doom-themes-org-config)

    ;; Enable custom treemacs theme (all-the-icons must be installed!)
    (doom-themes-treemacs-config))
```

**Comment by Alexander-Miller** [comment]
Old tickets housekeeping:
 - Treemacs now supports different themes - we only need people to make more
 - A more subtle approach is available with doom's theme
 - vscode icons will be added in #262

I think we can close here.
