### ISSUE TITLE
IDEA: right/left key bindings

### ISSUE THREAD

**Issue by avkoval** [Alexander-Miller/treemacs#29]
Hi,
Can I optionally bind right/left keys to:

 - right key opens leaf
 - left key should close current leaf
 
At least for me it could be useful. Right now it is not so straightforward to open/close as TAB and Enter are context-dependent, so sometimes they toggle, sometimes they open/change focus. If right/left keys are bind to those actions it will be straightforward to use for this specific action only.

That is just an idea, would be good if you suggest how to do this locally if this does not makes sense for all.

**Comment by Alexander-Miller** [comment]
I don't think TAB is all that complex. If a node is closed it's opened, and if it's open it's closed again. Only exception are tags. You cannot open and close them, so TAB just calls goto-definition on them.

Your wanting to work with nodes based on whether they are open and closed instead of whether they're files or dirs means there's no nice macro for you to use, but it should be easy enough. You can read a bit more about button properties on the wiki, but for now you'll need something like this:

```
(defun treemacs-open-closed-node ()
  (interactive)
  (-when-let (btn (treemacs--current-button))
    (pcase (button-get btn 'state)
      ('dir-node-closed
       (treemacs--open-node btn))
      ('file-node-closed
       (treemacs--open-tags-for-file btn))
      ('tag-node-closed
       (treemacs--open-tag-node btn))
      (_
       (treemacs--log "Current node is not closed.")))))
(define-key treemacs-mode-map (kbd "<right>") #'treemacs-open-closed-node)
```

Note that `treemacs--open-node` needs a better name. I'll probably rename it to something like `treemacs--open-dir-node` in the next version.

**Comment by avkoval** [comment]
For example I stay here:

![](http://scr.ua2web.com/avk/ss_20170807184830_F4VfRpjUbjdkIChZ2DHy.png)

so to close up to models.py I need to press UP * 4 and then TAB. With left key its just single press.
so all I want is to improve the speed of opening/closing the items.

**Comment by Alexander-Miller** [comment]
You can press u to jump to the next parent button, so for that scenario it'd be u u TAB.

A quick version is still possible, you'll need to write something like
```
(defun treemacs-close-nearest-file ()
  (interactive)
  (-when-let (btn (treemacs--current-button))
    (while (and btn
                (memq (button-get btn 'state) '(button types you want to skip)))
      (setq btn (button-get btn 'parent)))
    (when btn
      (pcase (button-get btn 'state)
        ('dir-node-open
         (treemacs--close-node btn))
        ('file-node-open
         (treemacs--close-tags-for-file btn))
        ('tag-node-open
         (treemacs--close-tag-node btn))
        (_
         (treemacs--log "Current node is not open."))))))
```
Basically just keep moving to the next parent button, until you find one with the type you want to close. In your case you'll probably want to be skipping tag buttons. You can read about button properties and states in the wiki.
