### ISSUE TITLE
fringe indicator is still shown after fringe indicator mode is disabled.

### ISSUE THREAD

**Issue by minad** [Alexander-Miller/treemacs#291]
It seems the mode is <del>disabled</del> enabled by default. When I deactivate it, the fringe is still shown but it doesn't move anymore with the highlighted line.

**Comment by Alexander-Miller** [comment]
You probably mean enabled by default? 

The indicator is a buffer-local overlay that sits in the fringe, when the mode is disabled all these overlays are deleted. Does it work if you manually call `(treemacs-run-in-every-buffer (treemacs--disable-fringe-indicator))`? After you've disabled it, what is the *local* value of `treemacs--fringe-indicator-overlay` in the treemacs buffer?

**Comment by minad** [comment]
It works if I use the following in my treemacs use-package config.

~~~ elisp
(setq treemacs-fringe-indicator-mode nil)
(treemacs-run-in-every-buffer (treemacs--disable-fringe-indicator))
~~~

**Comment by minad** [comment]
It would also be a bit more useful if a cursor would be shown instead of the fringe indicator if the treemacs window is active. Is it possible to show the cursor in the active treemacs window?

**Comment by Alexander-Miller** [comment]
> It works if I use the following in my treemacs use-package config.

The 2nd line will execute the first line in every treemacs buffer when the mode is disabled. So if that code works, then disabling should work, too. Can you show your entire treemacs config? I've the suspicion that it's an issue about loading order.

> Is it possible to show the cursor in the active treemacs window?

Nope. I've specifically disabled the cursor because I thought it looks bad, does not fit into treemacs since it doesn't have a (user-visible) column position and I don't do much about the cursor location other than make sure it's not on top of an icon since that would highlight the icon's borders. If you're sure you want to keep the cursor around I can add a config variable for it.

**Comment by minad** [comment]
> The 2nd line will execute the first line in every treemacs buffer when the mode is disabled. So if that code works, then disabling should work, too. Can you show your entire treemacs config? I've the suspicion that it's an issue about loading order.

here is my init.el https://gist.github.com/minad/0fef217296a3b61547904a78d94929a7
there is the usepackage treemacs init and then (treemacs) is called from some init hook.

> Nope. I've specifically disabled the cursor because I thought it looks bad, does not fit into treemacs since it doesn't have a (user-visible) column position and I don't do much about the cursor location other than make sure it's not on top of an icon since that would highlight the icon's borders. If you're sure you want to keep the cursor around I can add a config variable for it.

Yes, I agree that it does not look particularly nice. However I am accustomed to the cursor indicating the active window (besides the window frame color). I've not seen many special modes without cursor before, even if the cursor is not as useful as in a pure text buffer. I would prefer a configuration variable if it is not too much effort. You might also consider leaving the defaults and providing a treemacs hook for such settings, where something like that could be overwritten manually?

**Comment by Alexander-Miller** [comment]
`treemacs-show-cursor` is pushed to master.

Your config looks about right, but it doesn't show the code you used originally. If running the deactivation code manually works for you it's probably something in there. Did you call the minor mode with nil instead of -1?

> and providing a treemacs hook for such settings, where something like that could be overwritten manually?

No special hooks necessary, if you want to set some variable when treemacs launches you can use treemacs-mode-hook.

**Comment by minad** [comment]
Thank you! I called fringe-indicator-mode with nil instead of -1. It works with -1. I have seen that a few times that -1 is used for deactivation. Why is that?

**Comment by Alexander-Miller** [comment]
That's default emacs behaviour. If you `(define-minor-mode FOO)` then down the line it'll expand into
```
(setq FOO
            (if (eq arg 'toggle) 
                (not FOO)
              (> (prefix-numeric-value arg) 0)))
```
and `(prefix-numeric-value nil)` is 1, so it counts as enabling the mode.

**Comment by minad** [comment]
Thanks!
