### ISSUE TITLE
Can't get it to see my directories

### ISSUE THREAD

**Issue by chiply** [Alexander-Miller/treemacs#297]
I've installed and copied the config from the readme.  But whenever I evaluate treemacs, it can only see one directory - eshell.  Even using treemacs-find-file, it can only see the files in that one directory.  I have tried updating, uninstalling and reinstalling, playing with different python distributions.  Nothing seems to work. 

Any idea why this might be happening?

**Comment by Alexander-Miller** [comment]
Judging by your description you should read some parts the readme, at least the quickstart part. And yes, I know how large it is.

Treemacs isn't like neotree or nerdtree, but like the project explorer in eclipse. For the most part it expects you to work with projects organized in workspaces (it's really a work in progress and there's compromises made if you prefer a single file tree). So when it starts for the first time it'll ask you for the location and name of your first project. I guess that's what eshell is. So long as there's only one project around you can navigate back and forth with h & l (that's the compromise part).

There's various project management functions bound under the C-p prefix. which-key is a great help there, and the helpful hydra will list just about everything you need to know. Also `treemacs-projectile` (that's not in the hydra because it's from another package) can help you quickly add your projects.

Additionally you can look at exactly what treemacs has stored for you in the `treemacs-persist-file`. It's stored in org-mode format, so you can activate it there. And no, using it to edit your projects isn't possible yet. That's the work in progress part.

treemacs-find-file will only find and select the current file from among your projects. If it cannot find it you should see a red flash and an error message how file xyz doesn't fall under any project in the workspace.

Hope that helps.

**Comment by chiply** [comment]
Explicitly adding projects with treemacs-projectile was the missing piece.  Thanks
