### ISSUE TITLE
popwin compatibility

### ISSUE THREAD

**Issue by seagle0128** [Alexander-Miller/treemacs#300]
In README, popwin compatibility is clarified, but I noticed this PR https://github.com/Alexander-Miller/treemacs/pull/99 which removed the popwin advices. 

I don't know the background (maybe related to https://github.com/Alexander-Miller/treemacs/issues/98), but `treemacs` is not compatible with `popwin` now definitely. While opening `treemacs`, then open the `popwin` buffers, the `treemacs` is closed unexpectedly. I recreated this issue with bare Emacs 26.1 on macOS and Linux.

My config is https://github.com/seagle0128/.emacs.d.
Anyway I switch to shackle and no such compatibility issue (https://github.com/seagle0128/.emacs.d/commit/6158274195004ff19f383341c0f57a441219548b).

**Comment by Alexander-Miller** [comment]
This one's on popwin. The issue you're having is not due to treemacs, but a general problem popwin has with side windows. Now side-window behaviour has slightly changed between emacs 25 and 26, and  popwin hasn't been updated since 2015, so it's unlikely it'll be solved on that end.

Note that treemacs being a side-window is optional, you can change it with `treemacs-display-in-side-window`.
