### ISSUE TITLE
[suggestion] `treemacs-root-up` should keep the cursor

### ISSUE THREAD

**Issue by mpanarin** [Alexander-Miller/treemacs#311]
It's a general usability suggestion.

when using the `treemacs-root-up` the cursor should stay at the line of the child folder we moved from. 
```
child2
|   grandchild1
    grandchild2
```

`treemacs-root-up` should move us to parent dir with focus on child2, instead of the top element
```
Root
    child1
|   child2
    child3
```

**Comment by Alexander-Miller** [comment]
You know I had planned on closing this ticket today, but I've run into some cosmetic bugs that I need to fix first. So this should be ready in a couple days.

**Comment by mpanarin** [comment]
@Alexander-Miller saw the new feature in, Thanks a lot!

**Comment by Alexander-Miller** [comment]
Did I forget to close this issue with the fix? Oops.

**Comment by duianto** [comment]
There seems to be one case where this doesn't work in Windows 10.

When navigating up to `c:/`, then the project name `/` (first line) gets selected instead of the expected previous directory.

For example, if the directory structure looks like this:
```
c:/
  project
    dir1
    dir2
      subdir1
      subdir2
    dir3
```
and the current Treemacs project is at `subdir2`.

Navigating up `h` shows:
```
dir2
  subdir1
  subdir2  <-- this is selected, as expected (it was the previous directory)
```

`h` again:
```
project
  dir1
  dir2  <-- selected, as expected
  dir3
```

`h` again:
```
/  <-- selected, unexpected
  $Recycle.Bin
  Documents and Settings
  ...
  project
  ...
```

one would expect `project` to be selected since it was the previous directory.

It works as expected in Ubuntu 18.04.1, navigating up to `/` selects the previous directory.
