### ISSUE TITLE
invalid-function treemacs-is-path

### ISSUE THREAD

**Issue by Compro-Prasad** [Alexander-Miller/treemacs#313]
Messages buffer:
```
Error running timer ‘treemacs--follow’: (invalid-function treemacs-is-path) [3 times]
```

**Comment by Alexander-Miller** [comment]
> invalid-function treemacs-is-path

That's because it is a macro. I cannot reproduce this error, neither with my local version, nor using the spacemacs layer. The follow-mode module also correctly requires the macros module at compile time, so there's not much to go on here. You can try producing a stack trace by evaluating `treemacs--follow` manually, but I think there's a good chance a simple reinstallation will fix this.

**Comment by Compro-Prasad** [comment]
Stack trace automatically generated by timer:
```
Debugger entered--Lisp error: (invalid-function treemacs-is-path)
  treemacs-is-path("/home/compro/Downloads/github.com/Wilfred/remacs/rust_src/src/buffers.rs" :in-workspace)
  treemacs--find-project-for-buffer()
  treemacs--follow()
  apply(treemacs--follow nil)
  timer-event-handler([t 0 0 200000 nil treemacs--follow nil idle 0])
```

**Comment by Compro-Prasad** [comment]
Btw, I am using recent build of Emacs

**Comment by Compro-Prasad** [comment]
Its resolved but got another one: #314

**Comment by sergeyklay** [comment]
@Alexander-Miller 

Just get this after `treemacs-fihish-edit`:
```
[Treemacs] Edit completed successfully.
Error running timer ‘treemacs--follow’: (wrong-type-argument stringp nil) [2 times]
```

After <kbd>M</kbd>+<kbd>x</kbd> `treemacs-version` <kbd>RET</kbd>
```
[Treemacs] v2.5-2019.03.07 @ 26.1
Error running timer ‘treemacs--follow’: (wrong-type-argument stringp nil) [2 times]
```

```
Debugger entered--Lisp error: (wrong-type-argument stringp nil)
  expand-file-name(nil)
  vc-file-getprop(nil git-root)
  vc-git-root(nil)
  apply(vc-git-root nil)
  vc-call-backend(Git root nil)
  treemacs--git-status-process-function(nil)
  treemacs-goto-file-node("/home/klay/workspace/X/Y/Z.txt" #s(treemacs-project :name "foo" :path "/home/klay/workspace/X"))
  treemacs--follow()
  apply(treemacs--follow nil)
  timer-event-handler([t 0 0 200000 nil treemacs--follow nil idle 0])
```

Please note: I have initialized git project at `/home/klay/workspace/X`

**Comment by Alexander-Miller** [comment]
How did your layout look like before and after making your edit?

**Comment by sergeyklay** [comment]
@Alexander-Miller Like this:
 
![image](https://user-images.githubusercontent.com/1256298/54045628-cbd63580-41da-11e9-861e-88836d1316cb.png)

- A "sidebar" at the left with 2 projects under vcs at the same workspace
- A window with the code from the 1st project
- A help window

**Comment by Alexander-Miller** [comment]
I meant your treemacs layout - what projects did have in your workspace before and after making your edit, what nodes were expanded, what did you add and delete?

**Comment by sergeyklay** [comment]
Ah, got it! Well, I can't reliable answer to this question. In such cases, it is quite difficult to determine what exactly  may be useful in the next days. And my first reaction was to write you here. Frankly speaking, I was editing some PHP-based project, for which I was probably punished haha. I did not have expanded nodes in the treemacs' frame and I was removing the code in the main window. If this is possible, please let me know what steps need to be taken in the future so that I'll provide more complete information.
