### ISSUE TITLE
conflicts with helm-swoop

### ISSUE THREAD

**Issue by Opimenov** [Alexander-Miller/treemacs#343]
when treemacs buffer is open, doing helm-swoop on opened file does not work.

**Comment by Alexander-Miller** [comment]
You know "does not work" is a *really* terrible problem description. It's probably https://github.com/Alexander-Miller/treemacs/issues/225, but you'll have to tell me more to know for sure.

**Comment by Opimenov** [comment]
agreed. it was late. I haven't looked into what exactly going on, but here is what I'm seeing. When I have a treemacs buffer open when I try to do a helm-swoop command in another buffer in the same frame, results of the search show up. But navigating to the desired search item does not work. ( C-n / C-p Arrows, nothing) at first I thought that it could be that the line numbers don't match up and that confuses helm (since I had global linum mode enabled). after disabling global linum same behaviors remained.

**Comment by Alexander-Miller** [comment]
Does the fix at the bottom of #225 help?

What's your config look like? Doom, Spacemacs, self-made?

**Comment by Opimenov** [comment]
fix does not work. 
Config is self-made which could be the problem. [config](https://github.com/Opimenov/emacs_config/blob/master/config.org)

**Comment by Alexander-Miller** [comment]
Can you reproduce the problem without treemacs with just the following code:
```
(progn
  (delete-other-windows)
  (with-selected-window (display-buffer-in-side-window
                         (get-buffer-create "TEST BUFFER")
                         '((side . left)))
    (set-window-dedicated-p (selected-window) t)))
```

**Comment by Opimenov** [comment]
yes, the exact thing is happening.

**Comment by Alexander-Miller** [comment]
Then this is not a problem with treemacs, but an issue with helm-swoop's window selection.

Swoop cannot be shown in the side-window because it's strongly dedicated to showing its current buffer (as is treemacs), so it takes up the entire main window, not leaving any space to show the buffer it's actually swooping in. Which somehow breaks its navigation, go figure. At least that's what happens on my end when starting from `emacs -Q`.

Based on that I think the actual cause lies with either helm's or swoop's window selection and sizing,  and this is where you should raise your issue instead. Treemacs being the trigger is merely incidental.

In the near term you should be able to fix your problem by using something like [shackle](https://github.com/wasamasa/shackle) to control your helm windows' popup behavior.
