### ISSUE TITLE
Need package `pfuture-1.3', but only 1.2 is available

### ISSUE THREAD

**Issue by philipsd6** [Alexander-Miller/treemacs#344]
Installed per documentation, including the treemacs-magit package:

```elisp
  (use-package treemacs-magit
    :after treemacs magit
    :ensure t)
```
but that causes this error:

    Need package `pfuture-1.3', but only 1.2 is available

Seems odd because your Alexander-Miller/pfuture repo only has tagged up to 1.2, so I wouldn't expect a 1.3 anywhere. Not sure how to resolve this -- is it not ready to use yet? I see you're working on this as of an hour ago, so maybe not! :)

**Comment by Alexander-Miller** [comment]
> Installed per documentation

It's good to know there's people out there reading it, despite its size.

> Seems odd because your Alexander-Miller/pfuture repo only has tagged up to 1.2

That's because I forgot to push the new tag :/ I did push it now. You'll also want to wait until https://github.com/Alexander-Miller/treemacs/commit/1a30066872fa11612ab4ff8a8565beedb5f2e135 has been built.

Are you using melpa stable? I seem to distinctly remember package.el not being smart enough to actually check package versions.

**Comment by philipsd6** [comment]
Yes, I'm using melpa stable...

```elisp
(setq package-archives '(("marmalade" . "https://marmalade-repo.org/packages/")
                         ("melpa-stable" . "https://stable.melpa.org/packages/")
                         ("gnu" . "https://elpa.gnu.org/packages/")
                         ("org" . "https://orgmode.org/elpa/")))
```

Also, running into another error, I'll open another issue.

**Comment by Alexander-Miller** [comment]
Bump?

**Comment by philipsd6** [comment]
Solved. Not sure what change fixed it because I've changed everything -- built latest emacs, recreated my init from scratch...
