### ISSUE TITLE
file icon disappear when it is updated.

### ISSUE THREAD

**Issue by jayhanjaelee** [Alexander-Miller/treemacs#350]
I'm using emacs 26.1 on Mac OS and cask for emacs package manager. I'm using cask when package update is needed. So when I update treemacs using cask, its file icon is disappear. after I delete Treemacs package and reinstall it, its icon appears again.

**Comment by Alexander-Miller** [comment]
You mean file icons, right? 

When the icons are not there what is the value of `treemacs-icon-emacs`? It should look like this:
```
#("  " 0 1 (display (image :type imagemagick :file
  "/home/a/Documents/git/treemacs/icons/emacs.png" :scale 1 :ascent center
  :width 22 :height 22 :background "#2d2d31") img-selected (image :type
  imagemagick :file "/home/a/Documents/git/treemacs/icons/emacs.png" :scale 1
  :ascent center :width 22 :height 22 :background "#383844") img-unselected
  (image :type imagemagick :file
  "/home/a/Documents/git/treemacs/icons/emacs.png" :scale 1 :ascent center
  :width 22 :height 22 :background "#2d2d31")))
```

Are the paths valid, do they lead to the correct image?

**Comment by Alexander-Miller** [comment]
Bump

**Comment by zoechi** [comment]
For me the icons disappear frequently as well. I'm not sure yet what causes it.
I had the machine running overnight (locked) and when I came back the icons where not showing, only empty squares with a white border (dark theme).
C-h v treemacs-icon-emacs variable does not seem to exist.

**Comment by Alexander-Miller** [comment]
Did you recently update treemacs? The previously defined location of the
icons would change, so you need to restart when updating. However Emacs
does have a cache for images, so it can take a while until that cache is
flushed and you actually see that something's wrong, hence the problem
only appearing over night.

> C-h v treemacs-icon-emacs variable does not seem to exist.

The icon implementation changed a great deal since this issue was first
opened. Nowadays you need to get an icon value with
`(treemacs-get-icon-value 'root)`.

**Comment by zoechi** [comment]
@Alexander-Miller  I see, thanks for the info 
and this super useful package :+1:

**Comment by Alexander-Miller** [comment]
Since OP is in the same boat I'll be closing here.
