### ISSUE TITLE
Don't auto-expand symlinks on project root

### ISSUE THREAD

**Issue by memeplex** [Alexander-Miller/treemacs#378]
I've reported this for projectile but it seems like treemacs has the same behavior.

See the description [there](https://github.com/bbatsov/projectile/issues/1387) to understand why this behavior might be undesirable.

**Comment by Compro-Prasad** [comment]
I prefer if symlinks are followed.

**Comment by memeplex** [comment]
Then set your root with the symlink already expanded. The point here is to honour the root as set by the user, not to force some specific behavior. I'm changing the subject, maybe it's confusing.

**Comment by Compro-Prasad** [comment]
But there can be multiple projects pointing to the same symlink. It would be good to not allow opening multiple projects pointing to the same symlink.

**Comment by Alexander-Miller** [comment]
I'm afraid I will have to refuse this one. First because of this:

> But there can be multiple projects pointing to the same symlink.

Treemacs cannot deal with a file appearing twice in a workspace, so that could break it in subtle ways.

Then there's this:
 - https://github.com/Alexander-Miller/treemacs/issues/218
 - https://github.com/Alexander-Miller/treemacs/issues/210

Put together that is far more trouble than I am willing do deal with.

I don't know what your config looks like, but you should be able to keep your symlinks as they are, and just use `file-truename` in your config. I use the same pattern with `expand-file-name` to expand "~" and get around different user names without issue.

**Comment by memeplex** [comment]
Ok, I wasn't saying that treemacs internally uses other than the true name, but just that it shows it as the user configured it intead of fully resolved. But this might be complicated to implement, as you said, that I don't know. The way I'm dealing with this now is by advicing file-truename.

**Comment by Alexander-Miller** [comment]
> but just that it shows it as the user configured it instead of fully resolved

Show where?

**Comment by memeplex** [comment]
At least in buffer-file-name.

**Comment by Alexander-Miller** [comment]
In that case

> treemacs internally uses other than the true name, but just that it shows it as the user configured it instead of fully resolved.

this kind up setup would have me keep some project-specific cache of linked-name vs real-name, and then struggle against emacs' own link-chase settings. So yeah, not worth the trouble.
