### ISSUE TITLE
Fallback when python3 is missing is very slow

### ISSUE THREAD

**Issue by michaelpj** [Alexander-Miller/treemacs#406]
After updating treemacs, I observed that it would hang upon opening with my large-ish project. Eventually I tracked this down to `treemacs--collapsed-dirs-process` and noticed that this had started requiring `python3`. Installing `python3` made it snappy again.

It did work on smaller projects, however, so I deduce that there is some kind of fallback, but that it's very slow. I would really prefer to just get an error that tells me that I need to install `python3`, rather than have tricky-to-diagnose slowness.

**Comment by Alexander-Miller** [comment]
There is no slow fallback, just a blind spot when no python binary is found. Apparently emacs lets you start processes with `nil` as the command to run, and they even keep running somehow instead of crashing or never starting. Go figure.

I can fix that no problem, but this is not the cause of the slowness you experience. The real culprit is git-mode, which switches to a largely synchronous elisp implementation when there is no python3 binary. That is why things got fast again when you installed python3.

Even so, simple git-mode is not *that* slow and it only looks at individual files, it does not comb through every ignored file in a directory. You should not feel slowness unless you have hundreds or even thousands of git status entries to go through. So if you want to know what exactly treemacs is seeing run the following code on a slow project (remove the count call to see the actual hash table of status entries that is produced):

```Lisp
(-> "/home/a/Documents/git/treemacs"
    (treemacs--git-status-process-simple)
    (treemacs--parse-git-status-simple)
    (hash-table-count))
```

**Comment by michaelpj** [comment]
Hm, interesting. I wonder if it was actually waiting for the process to return? It was definitely *not* in the git-mode function, I `SIGUSR2`'d the process and it was waiting for `treemacs--collapsed-dirs-process`.

If that's true, I'm not sure why it would have behaved any differently on another project, though.

**Comment by Alexander-Miller** [comment]
My bad, you're right, it's still possible for dir collapsing to be the cause here, installing python3 would have fixed it as well since the python-binary variable is no longer nil. In fact that's for the best, the fix is trivial now.

**Comment by michaelpj** [comment]
Fwiw I still think it would be nice to give some kind of warning if python isn't there, otherwise the user has no idea it might be needed!

**Comment by michaelpj** [comment]
Thanks for the quick fix!

**Comment by Alexander-Miller** [comment]
> Fwiw I still think it would be nice to give some kind of warning if python isn't there

Why not, might as well advertise the goods.

Note that these warnings happen during *load-time* so you cannot just custom-var them away. See the part about `no-load-time-warnings` in the readme.
