### ISSUE TITLE
evil-escape causes treemacs to lose most bindings

### ISSUE THREAD

**Issue by fiveNinePlusR** [Alexander-Miller/treemacs#434]
reproduction steps:

in spacemacs `spc f t` then `jk` to exit insert mode press `?`

expected results: show the helpful hydra with a bunch of bindings. 

actual results: normal mode `?` binding exists.

calling `treemacs-helpful-hydra` manually shows most bindings are missing. 

pressing `i` to enter insert mode enables the bindings again.

**Comment by Alexander-Miller** [comment]
AFAICT it's up to evil-escape to add proper bindings for `treemacs-quit`, so the best I can do is tell it to ignore treemacs.

**Comment by fiveNinePlusR** [comment]
Right now it puts it into normal mode with a bunch of missing bindings... perhaps treemacs could start in normal mode like it did in the past instead of insert mode?

**Comment by Alexander-Miller** [comment]
I cannot remember that treemacs ever started in insert-state. It uses its own specialized treemacs-state, which is based on motion-state. Getting the keybinds back in insert state is coincidental since most normal keys are bound to just self-insert, so treemacs can take precedence.

At any rate I've gone ahead and created a PR in https://github.com/syl20bnr/evil-escape/pull/89. Let's hope it gets merged in time.

**Comment by fiveNinePlusR** [comment]
i guess i'm just going to add treemacs-mode as evil-escape ignored though the other patch should probably be merged. you can close this if you'd like or leave it open until the other one is merged for people like me that were a bit confused.

**Comment by Alexander-Miller** [comment]
No need, I'll add the change to treemacs myself. It should be ignored for everyone while proper compatibility is not there yet.

The change will be reverted again whenever my PR gets merged, but I won't keep this issue open until then, so I suggest you subscribe to https://github.com/syl20bnr/evil-escape/pull/89.
