### ISSUE TITLE
Treemacs stopped working after upgrade

### ISSUE THREAD

**Issue by jschaeff** [Alexander-Miller/treemacs#44]
Hi,

after upgrading treemacs, the tree is not visible and I have this error message:

  [Treemacs] Error on highlight, this shouldn't happen: (wrong-type-argument number-or-marker-p nil)

Version on MELPA :  20170910.1406

**Comment by Alexander-Miller** [comment]
That should not stop treemacs from working, the error is supposed to be caught, the message you see is just debug info I kept in since I wasn't sure how robust the system is.

The error appears in a system I built to change the background color of png icons when they're highlighted with hl-line mode, so you need to tell me what the directory treemacs should show looks like and which line is selected when the error occurs.

**Comment by Alexander-Miller** [comment]
Just pushed a fix for an edge case that triggers this bug when treemacs is showing an empty directory. Check if it works now.

**Comment by Alexander-Miller** [comment]
Is this still relevant? How's the newest (yesterday's) version working out for you?

**Comment by jschaeff** [comment]
Great, latest version is working.

Thank you !
