### ISSUE TITLE
treemacs-projectile-toggle doesn't respect current buffer project

### ISSUE THREAD

**Issue by brettatoms** [Alexander-Miller/treemacs#51]
When calling `treemacs-projectile-toggle` I would expect it to check the project of the current buffer and use it for the root of the tree when opening a new treemacs view.  At the moment it seems to use the path of when `treemacs-projectile-toggle` was first called.

**Comment by Alexander-Miller** [comment]
That's working as intended. It's a counterpart to `treemacs-toggle` which shows the treemacs buffer if it exists, and creates a treemacs buffer for the current directory otherwise. projectile-toggle is the same - show treemacs if it already exists, and create a new treemacs buffer for the current project if it does not.

The toggle functions are a means to quickly show/hide treemacs. If you want treemacs to show your current project regardless of what it's showing already just call `treemacs-projectile`. Same for `treemacs` and the current directory.

You can also call `treemacs`/`treemacs-projectile` with a prefix arg to manually select the directory/project to display.
