### ISSUE TITLE
Improve window resizing

### ISSUE THREAD

**Issue by Alexander-Miller** [Alexander-Miller/treemacs#514]
See https://github.com/Alexander-Miller/treemacs/issues/41

**Comment by jjforsythe** [comment]
Currently it looks like the `balance-windows` function does not work as expected if the treemacs window does not have a fixed width. The treemas window will be resized, as opposed to remaining the same size. There may also be an issue for similar functions such as `balance-windows-area` which are discussed in #41, although I haven't tested this. This appears to be associated with this Spacemacs issue: https://github.com/syl20bnr/spacemacs/issues/12641.
It would be helpful to confirm the scope of this issue so it can be determined whether a bug fix is required within Spacemacs.
A possible solution could be to add an advice around the affected functions, similar to the fix for the which-key issue in 507da48d84d61759b8d96c56d0920a815b1e2915, alternatively it has been proposed by @andreyorst in #41

**Comment by jjforsythe** [comment]
Hopefully this comment is relevant to the scope of this issue.

Currently it looks like the `balance-windows` function does not work as expected if the treemacs window does not have a fixed width. The treemacs window will be resized, as opposed to remaining the same size. There may also be an issue with similar functions such as `balance-windows-area`, which are discussed in #41, although I haven't tested this.

This appears to be associated with this Spacemacs issue: syl20bnr/spacemacs#12641. It would be helpful to confirm the scope of this issue so it can be determined whether a bug fix is required within Spacemacs.

A possible solution could be to add an advice around the affected functions, similar to the fix for the which-key issue in 507da48. Alternatively, @andreyorst proposed the followinng on #41:
> It also would be nice if treemacs could become re-sizable when user attempts to resize, but after resize it will use fixed size, so treemacs couldn't be resized by resizing the frame.

**Comment by Alexander-Miller** [comment]
> It also would be nice if treemacs could become re-sizable when user attempts to resize, but after resize it will use fixed size, so treemacs couldn't be resized by resizing the frame.

That's been added now. Resizing with the mouse will work regardless of width settings.
