### ISSUE TITLE
treemacs-find-file can't open the right file in treemacs buffer

### ISSUE THREAD

**Issue by zijianyue** [Alexander-Miller/treemacs#522]
Create a project in a folder like below which is a  git repo, then in abc.java trigger treemacs-find-file, it can't open the right file in treemacs buffer.
![image](https://user-images.githubusercontent.com/6119928/63822690-bd93f580-c983-11e9-88da-a91cf07d1bca.png)
But when I unfold the top folder service manually, it works well as below
![image](https://user-images.githubusercontent.com/6119928/63822438-e4056100-c982-11e9-9748-4dc5ebe91564.png)

**Comment by Alexander-Miller** [comment]
This bug is due to having a single directory inside a directory. Normally this setup gets flattened into a single node, like with your ApiTest dir, but the thing is still bugged in some places.

This entire area will be overhauled as part of https://github.com/Alexander-Miller/treemacs/issues/226, so it makes little sense to look into this bug right now. For now you should be able to get things working by just killing the treemacs buffer and summoning it again. You can also set `treemacs-collapse-dirs` to 0 as a workaround.

**Comment by zijianyue** [comment]
OK, waiting for your improving.

**Comment by Alexander-Miller** [comment]
Let's keep this open. This is a legitimate bug, and I'd like a reminder to make sure it's working when I'm done with the overhaul.

**Comment by Alexander-Miller** [comment]
Fixes have been pushed. Try again with the latest version.

**Comment by zijianyue** [comment]
treemacs-find-file still can't open the right file in treemacs buffer until I open the "service" folder.
![image](https://user-images.githubusercontent.com/6119928/68364723-c36b3b80-0169-11ea-988f-7bc8ae414d30.png)

![image](https://user-images.githubusercontent.com/6119928/68364797-f6adca80-0169-11ea-9004-318960009d87.png)

**Comment by Alexander-Miller** [comment]
Confirmed. I'll look into this.

**Comment by Alexander-Miller** [comment]
Next attempt. Pushed another fix, try again now.

**Comment by zijianyue** [comment]
OK, it worked well now
