### ISSUE TITLE
[Question] desktop.el compatibility

### ISSUE THREAD

**Issue by andreyorst** [Alexander-Miller/treemacs#563]
Readme states:

>**Session Persistence**
>Treemacs’ sessions - your workspace and the projects it contains - are saved when Emacs shuts down and restored when treemacs is first loaded. This persistence process is fully automatic and independant, and should therefore be fully compatible with `desktop-save-mode`.
>
>The persisted state is saved under `user-emacs-directory/.cache/treemacs-persist` by default. The exact file location is saved in the variable `treemacs-persist-file`.
>
>If something goes wrong when loading the file the erroneous state will be saved in `treemacs-last-error-persist-file` for debugging.

Which allows workspaces to be stored between sessions. But upon enabling `desktop-save-mode` I've expected that last active workspace would be restored as well. Is it possible to do?

**Comment by andreyorst** [comment]
weird. It seem to work on another PC

**Comment by Alexander-Miller** [comment]
Treemacs is not compatible with desktop-save-mode, but independent of it. Your session is saved either way.

When you start treemacs it will select the first workspace that contains the file you are currently in, and falls back to just using the first one in the list. That should explain why it worked on another computer.

**Comment by andreyorst** [comment]
I guess I can advice some desktop function to call some Treemacs function to restore the workspace, which would require storing workspace on disk when session is saved. Maybe there's easier way though?

I wonder If Treemacs could indicate last used workspace in the `treemacs-persist` file like this:

```org
* Workspace 1
- [ ] last used
** project 1
 - path :: /some/path
* Workspace 2
- [x] last used
** project 1
 - path :: /some/path
```

**Comment by Alexander-Miller** [comment]
The problem with this is that there is more than one last used workspace. Workspaces are local to frames, you could open 5 frames showing 5 workspaces, which one would be that last then?

I had given up on desktop-save-mode precisely because this + order of restoring frames & buffers + maybe restoring things lazily would never work quite right.

I did however just remember that treemacs lets you set the workspace it picks if it can't the right one for the current file. Does `(add-hook 'treemacs-switch-workspace-hook #'treemacs-set-fallback-workspace)` do the trick for you?

**Comment by andreyorst** [comment]
> The problem with this is that there is more than one last used workspace. Workspaces are local to frames, you could open 5 frames showing 5 workspaces, which one would be that last then?

Probably the one from the instance was closed the last. But I see your point. I'll try fallback workspace feature.
