### ISSUE TITLE
More pictures

### ISSUE THREAD

**Issue by Alexander-Miller** [Alexander-Miller/treemacs#575]
Nobody reads so large a readme anyway, and there's plenty of useful features that can quickly be demonstrated with gifs.

**Comment by mrspeaker** [comment]
Ha ha, I just found this project and was thinking of testing it out (I'll try it after work! I'm using neotree, but development on that seems to have stalled)... I was a bit worried that treemacs was "overkill" for my needs, because the readme was so long - and then after reading it all I realized it wasn't that crazy, just long: so +1 for more pictures ;)

**Comment by Alexander-Miller** [comment]
There's plenty of options and what not, but I like to think that the defaults are still sane :man_shrugging:.
