### ISSUE TITLE
treemacs--buffer-access void variable

### ISSUE THREAD

**Issue by andreyorst** [Alexander-Miller/treemacs#576]
Running `M-x treemacs RET` inside Emacs 27 gives this error:

```
treemacs-fringe-indicator-mode: Symbol’s value as variable is void: treemacs--buffer-access
```

Melpa version: 20191203.1609

**Comment by Alexander-Miller** [comment]
That part has been rebuilt for #222. The variable has been renamed to treemacs-buffer-storage and no longer exists in the code base:
```
[I]-(a@a-laptop)-(/home/a/Documents/git/treemacs)-(master)
❯❯❯ rg "treemacs-buffer-access" | wc -l
0
```

Did you restart emacs after you updated? Some old defvar or inlined function may have stuck around.

**Comment by andreyorst** [comment]
yes. there's double dash `--` though, while you're doing search with
single. I've also disabled my configuration but still got the error

**Comment by Alexander-Miller** [comment]
> yes. there's double dash `--` though

Yes there is, but it doesn't change the result:

> [I]-(a@a-laptop)-(/home/a/Documents/git/treemacs)-(master)
❯❯❯ rg "buffer-access" | wc -l
0
[I]-(a@a-laptop)-(/home/a/Documents/git/treemacs)-(master)
❯❯❯ git diff | rg "buffer-access" | wc -l
0

So that concludes my search :man_shrugging: . Try reinstalling. If that doesn't help show me what debug-on-error gives you.

**Comment by andreyorst** [comment]
reinstalling helped, thanks
