### ISSUE TITLE
Is there a way to hide file extensions?

### ISSUE THREAD

**Issue by TonCherAmi** [Alexander-Miller/treemacs#584]
I have a project that only contains org files so I think it would look way cleaner without file extensions, like so:
```
- Personal
 Main
 Auxiliary
```
rather than the way it is now:
```
- Personal
 Main.org
 Auxiliary.org
```

EDIT: If this is not currently possible I'd appreciate if you could point out the function that handles node rendering, thanks.

**Comment by Alexander-Miller** [comment]
It is neither possible, nor could you hack it yourself without unreasonable overhead. The whole render module consists of nothing but macros and inlined functions - advising or overriding will do nothing here (it's `treemacs--create-branch` calling `treemacs--create-file-button-strings` that's responsible for creating those file names).

However I wouldn't mind seeing such a feature - it can be done fairly easily and without performance loss, so if you don't mind getting into it yourself I can guide you on what to do. Otherwise my policy is that the backlog takes priority over new feature requests, so it'll be a while till I will get to this.

**Comment by TonCherAmi** [comment]
I think I might take a swing at it if I can find the time. I'm thinking sticking the logic somewhere in `treemacs--get-dir-content` would be the right way to go about it? Also I guess it might be better to allow the users to specify their own mapping function to alter filenames in any way they might desire rather than only permitting optional extension stripping.
