### ISSUE TITLE
Space in the treemacs buffer prefix

### ISSUE THREAD

**Issue by Sasanidas** [Alexander-Miller/treemacs#636]
Hello
I was trying to hide the buffer name for the treemacs buffer, when I find that the buffer name has a space as first character... so my hide tabs functions for centaur tabs didn't work.
``` lisp

(defconst treemacs--buffer-name-prefix " *Treemacs-")

```
With just removing the initial space, all seems to work fine for my config, i don't know if it is a bug or if the name is fine, in any case.
Thank you!

**Comment by Alexander-Miller** [comment]
That is intentional. A leading space marks a buffer as basically a private implementation detail that should not be visible to the user. Treemacs is far from the only package making use of that feature:

```Elisp
(dolist (b (buffer-list))
  (when (s-starts-with? " " (buffer-name b))
    (message "%s" b)))
```
```
 *mu4e-loading*
 *Minibuf-1*
 *Treemacs-Scoped-Buffer-#<frame emacs@a-laptop 0x1226c60>*
 *mu4e-main*
 *Minibuf-0*
 *code-conversion-work*
 *Echo Area 0*
 *Echo Area 1*
 *server*
 *helm candidates:Search at search.el*
 *org-src-fontification:emacs-lisp-mode*
 *mu4e-proc*
 *ivy-posframe-buffer*
 *temp*
 *pfuture stderr dummy*
```

I don't know what centaur tabs' api looks like, but checking for a buffer like treemacs should be as simple as `(= ?\ (aref (buffer-name buffer) 0))` or `(eq 'treemacs-mode (buffer-local-value 'major-mode buffer))`

**Comment by Sasanidas** [comment]
That's the thing, centaur tabs was putting that Treemacs buffer name on the top, so it was looking quite bad.
But it seems like is a centaur tabs issue, not related to treemacs.
Thank you!
