### ISSUE TITLE
I updated treemacs and lost all of my project roots.

### ISSUE THREAD

**Issue by simurgh9** [Alexander-Miller/treemacs#653]
I updated treemacs and lost all of my project roots and now when I try to add a project I get the following,

```
Error running timer: (wrong-type-argument integer-or-marker-p nil)
```
Help!

**Comment by Alexander-Miller** [comment]
First things first: you probably see the timer error because the treemacs buffer is in a borked state, just kill it. You can try to get your stuff back by using `treemacs-edit-workspaces`, or even edit the `treemacs-persis-file` directlly.

 Did you restart Emacs when you updated?  You should always restart when updating packages, so new code does not get mixed in with the old.

Did treemacs log anything when stuff got lost or did you seen any other errors?

Has your old state been saved in `treemacs-last-error-persist-file`?

**Comment by simurgh9** [comment]
I restarted my computer and everything came back. I was in the middle of an important project and had to update several packages and treemacs got in as one. Then when it broke, I freaked out because I use it a lot. I did try restarting emacs but for some reason it just won't work. I posted the question and restarted my computer which made it work correctly again (probably should have waited to post the question till after the restart ...).

Thank You for replying though :)

**Comment by simurgh9** [comment]
Oh, I meant to ask, I don't think I saw workspaces in treemacs before. What is the difference between a workspace and a project root node?

**Comment by Alexander-Miller** [comment]
A workspace is just a collection of projects. Think of it as a context like "work stuff" and "private stuff" for you to switch as appropriate.

Workspaces are scoped to Emacs frames, using treemacs-persp lets you scope them to perspectives.

**Comment by simurgh9** [comment]
Is it now possible to have `root/dir0/` in a worspace and `root/dir0/dir1` in another at the same time?

**Comment by Alexander-Miller** [comment]
Workspaces are independent, so that has always been possible. It's putting them in the same workspace that's not allowed.
