### ISSUE TITLE
Close treemacs buffer when pressing M-0 while treemacs is in focus

### ISSUE THREAD

**Issue by TimoFreiberg** [Alexander-Miller/treemacs#661]

**Comment by Alexander-Miller** [comment]
Wanna live code it? ;)

**Comment by Compro-Prasad** [comment]
IMO this is more of a keybinding behaviour change.

**Comment by Compro-Prasad** [comment]
`M-x treemacs` can already do a lot of things alone. Instead of it just toggling treemacs it can do the following:
1. When no treemacs window is opened then open treemacs. Don't switch automatically.
2. When treemacs window is being shown then switch to the treemacs window.
3. When in a treemacs window close treemacs if last command was also treemacs else switch to the last window that wasn't treemacs.

**Comment by Alexander-Miller** [comment]
Ah, I completely forgot about that. Looks like the issue is obsolete, right @TimoFreiberg?

**Comment by Compro-Prasad** [comment]
@Alexander-Miller What @TimoFreiberg is asking for is a mix of `treemacs` and `treemacs-select-window`. I just suggested that we can drop `treemacs-select-window` and make `treemacs` a bit more intelligent.

**Comment by Alexander-Miller** [comment]
Stayin alive.

The implementation will be quote a bit more straightforward now that we have `treemacs-select-when-already-in-treemacs`.
