### ISSUE TITLE
Conflict between Treemacs and flip-frame, flop-frame?

### ISSUE THREAD

**Issue by taquangtrung** [Alexander-Miller/treemacs#667]
Hi,

When Treemacs is enabled, if I run the commands `flip-frame` or `flop-frame`, there the Treemacs window will be duplicated, and all Emacs windows still remain in the same positions.

Could you help to check if this is an issue of Treemacs?

**Comment by Alexander-Miller** [comment]
There is nothing special about treemacs' window, all it does is call the builtin `display-buffer-in-side-window`. So the problem you see is most likely caused by the frame-flipping package getting confused by side-windows.

It might help if you set `treemacs-display-in-side-window` to nil (don't forget to reopen treemacs), but if not there is nothing else I can do.

Besides, if you want put treemacs on the right of your frame you can use `treemacs-position`.
