### ISSUE TITLE
Error opening under -Q from 27_2 GNU win10 binary dist

### ISSUE THREAD

**Issue by mplscorwin** [Alexander-Miller/treemacs#678]
Greetings!  I'm having some trouble with Treemacs since upgrading from Emacs 26.3.  Sorry  for not reporting issues until things had come to this point where things don't load at all.

Is there a set of cleanup activities I should try to see if this could be self-inflicted from bad cache files of some sort?  I'd be happy also to attempt to collect whatever diagnostic information may be of use, as well.

Thank you!

## Expected behavior

Treemacs should open without raising an error.

## Actual behavior

```
Debugger entered--Lisp error: (wrong-type-argument arrayp nil)
  treemacs--init()
  treemacs()
  (progn (toggle-debug-on-error) (load-library "package.elc") (package-initialize) (load-library "treemacs.elc") (treemacs))
  eval((progn (toggle-debug-on-error) (load-library "package.elc") (package-initialize) (load-library "treemacs.elc") (treemacs)) t)
  command-line-1((#("-eval" 0 5 (charset windows-1252)) #("(progn (toggle-debug-on-error) (load-library \"pack..." 0 122 (charset windows-1252))))
  command-line()
  normal-top-level()
```

## Steps to reproduce the problem

```
runemacs -Q -eval "(progn (toggle-debug-on-error) (load-library \"package.elc\") (package-initialize) (load-library \"treemacs.elc\") (treemacs))"
```

## Environment & Version information

Windows 10, 64 Home

### Projectile version information

```
[Treemacs] v2.8 (installed 2020.05.12) @ Emacs 27.0.90
```

### Emacs version

GNU Emacs 27.0.90 (build 1, x86_64-w64-mingw32) of 2020-03-23

Binaries from here:  
  https://alpha.gnu.org/gnu/emacs/pretest/windows/emacs-27/emacs-27.0.90-2-x86_64-installer.exe

### Operating system

Windows 10x64,. Home

**Comment by mplscorwin** [comment]
FWIW, I was able to resolve this by reinstalling treemacs from Melpa.  Please do close, if that seems best or, as I say, I'm happy to help in researching.

**Comment by Alexander-Miller** [comment]
> Is there a set of cleanup activities I should try to see if this could be self-inflicted from bad cache files of some sort?

Throw everything out and reinstall. I get reports like this, where some macro or similar is apparently not working right, one or twice a year and reinstalling always helps. I don't really know the real cause, but I assume it's just some compiler blooper.

In your case it looks like the `current-workspace` call returned nil which should never happen because if there is no current workspace treemacs will make one, so that definitely fits the bill.

> I'd be happy also to attempt to collect whatever diagnostic information may be of use, as well.

Re-evaluating treemacs' files can help. I use quite a bit of inlining, so using the plain interpreter could at least add some funcall details to the stack trace that would've been invisible otherwise.

There's also a `clean-start` make target you can use to start just treemacs that makes reproduction much easier (assuming cask can work on windows).

With that in mind I think we can consider the issue solved.

**Comment by mplscorwin** [comment]
I love macros.  Thanks for the details; if that helps me track anything down I'll be sure to reopen or maybe suggest a PR.

Thanks for great detail and a fantastic Emacs feature!
