### ISSUE TITLE
perspective.el vs persp-mode for Treemacs-persp

### ISSUE THREAD

**Issue by SreenivasVRao** [Alexander-Miller/treemacs#687]
Hi, I'm interested in using perspective.el for frame management. I see it has a name clash with persp-mode for some functions. 

Will this affect treemacs-persp? I see you explicitly require persp-mode package. Is there a reason to choose one over the other? 

Thanks!

**Comment by Alexander-Miller** [comment]
> Will this affect treemacs-persp? I

I'm not sure I understand your intended setup. Since treemacs-persp strictly needs persp-mode do you want to run both packages at the same time? Given the name clashes you describe I think treemacs integration is probably the least of your problems.

> Is there a reason to choose one over the other?

I asked and persp-mode was the answer I received. AFAIK both doom and spacemacs use persp-mode, so I guess it's a matter of popularity.

**Comment by jkdufair** [comment]
@SreenivasVRao I just decided to try and resolve this myself too! Didn't know about this issue. If you have time, would you be willing to test #688?
