### ISSUE TITLE
Error message while expanding project root.

### ISSUE THREAD

**Issue by simurgh9** [Alexander-Miller/treemacs#697]
I get the following message each time I expand a project root. I recently updated to Kubuntu 20.04 and I don't think I noticed this error message before. I have plenty of space left on my device.

`treemacs--expand-root-node: Could not add watch for file: No space left on device, /home/tf/Dropbox/Code`

Also, the project node is expanded fine after the error message is logged in `*messages*` buffer. Any ideas?

**Comment by Alexander-Miller** [comment]
The upgrade probably changed the limit for active file watches, or your system now creates more. Have a look at the ENOSPC entry from the FAQ: https://github.com/Alexander-Miller/treemacs#faq

**Comment by simurgh9** [comment]
Okay so I might need some clarification here, the filewatch mode watches the things like the name of the file and if it is deleted, etc, right? To be able to show the proper tree in treemacs. This does not include the contents of the file right? Because if I change the file with some other text editor and come back, I have to select that file and answer yes when Emacs asks that the file has been changed on the disk and if I would like to load it.

Also, from the FAQ section you pointed me to,

> ... treemacs only watches the directories it is displaying and so won’t produce more than a couple dozen watches at best.

How can we say that without knowing how many files are under the root/project node? If there are more than a dozen (which is the case for me) than wouldn't it generate more filewatches, one for each file under root.

Lastly, FAQ points to [this](https://stackoverflow.com/questions/16748737/grunt-watch-error-waiting-fatal-error-watch-enospc) stackoverflow question. It asks to increase the filewatch limit like so:

```
echo fs.inotify.max_user_watches=524288 | sudo tee -a /etc/sysctl.conf && sudo sysctl -p
```

What is a good number for this in our case or how should I figure this out? I do have dropbox running the back aswell.

**Comment by Alexander-Miller** [comment]
> filewatch mode watches the things like the name of the file and if it is deleted, etc, right?

Yes.

> This does not include the contents of the file right? Because if I change the file with some other text editor and come back, I have to select that file and answer yes when Emacs asks that the file has been changed on the disk and if I would like to load it.

That is a vanilla Emacs feature, treemacs has nothing to do with that. But treemacs does also listen for file change events (the ones caused by actually writing to disc) to refresh single files' tags or their git highlighting.

> How can we say that without knowing how many files are under the root/project node?

Because treemacs does not watch single files, but entire directories. That is why you only see the error message when you expand a directory - that's when a new filewatch is started. Maybe some implementations are different, but for me expanding a node creates just one filewatch (unless there's flattened directories involved, those require their own special attention).

I found this thing on SO that shows how much space Emacs takes up (don't ask me to explain, I can't). Take  away the last grep and you'll see a sorted list for your entire system.

```bash
find /proc/*/fd -lname anon_inode:inotify -printf '%hinfo/%f\n' 2>/dev/null | xargs grep -c '^inotify' | sort -n -t: -k2 -r | grep $(pgrep emacs)
```

> What is a good number for this in our case or how should I figure this out?

I have absolutely no idea how these things work under the hood. My own Manjaro default settings look like this:
```bash
❯❯❯ sysctl fs.inotify
fs.inotify.max_queued_events = 16384
fs.inotify.max_user_instances = 1024
fs.inotify.max_user_watches = 524288
```
I guess that's a start :man_shrugging:

**Comment by simurgh9** [comment]
I suppose I will not be as confused if it was called directorywatch than filewatch haha. Running, `echo fs.inotify.max_user_watches=524288 | sudo tee -a /etc/sysctl.conf && sudo sysctl -p` fixed my issue. What it did was that it wrote `fs.inotify.max_user_watches=524288` at the end of file `/etc/sysctl.conf` and I could check that using `emacs /etc/sysctl.conf`. Than, `sudo sysctl -p` must have just reloaded the file. Now the output of `sysctl fs.inotify` looks like this:

```shell
fs.inotify.max_queued_events = 16384
fs.inotify.max_user_instances = 128
fs.inotify.max_user_watches = 524288
```

Thanks!
