### ISSUE TITLE
alignment problems with all-the-icons theme

### ISSUE THREAD

**Issue by lcacciari** [Alexander-Miller/treemacs#705]
I tried the new all-the-icons theme but there are some alignment problems.

1. In the tree list, when a directory is open plain file icones show right under the (open) directory icon (sub directories are correctly indented)
2. In dired mode, plain file icons are shifted to the right w.r.t directory icons

(good job, BTW, I was looking for something like treemacs since a long time)

**Comment by Alexander-Miller** [comment]
Are you seeing the same thing as I am in the comments in #702?

It doesn't happen on a clean config for me, I'm currently tracking the exact cause.

**Comment by lcacciari** [comment]
This is what I get (I also added the two dired windows to show how directories are structured (and the problem I've there 
![Screenshot_2020-08-05_10-39-45](https://user-images.githubusercontent.com/1478882/89391783-f0547b00-d708-11ea-8960-6a82021a7458.png)

This is how it appears with the default theme:
![Screenshot_2020-08-05_10-49-14](https://user-images.githubusercontent.com/1478882/89392161-7244a400-d709-11ea-96f4-1b26efa392a6.png)

The difference seems to be in the directory  entries having an _arrow thing_ just before them. Would a padding of the plain file icons solve the problem?

**Comment by Alexander-Miller** [comment]
The problem is the font. I don't know what you use, but I see the same thing with Fantasque Sans Mono. For whatever reason tab widths go completely crazy with some fonts, but stay sane with others.

The good news is that I have a workaround in the works that will at least make things a lot less bad. I've also pushed a patch to sets tab-width to 1, so those excessively wide tabs are also taken care of now.

**Comment by Alexander-Miller** [comment]
Workaround is ready: https://github.com/Alexander-Miller/treemacs#all-the-icons-indent-issues
You just need to pick the right font.
