### ISSUE TITLE
Speedbar-like frame?

### ISSUE THREAD

**Issue by Whil-** [Alexander-Miller/treemacs#716]
Hi!

Maybe less of an issue and more of an inquiry. I'm wondering if you've considered adopting a frame-layout similar to how speedbar does it?

The reason for asking is that I find treemacs somewhat intrusive to my current frame when I'm opening it, and I haven't found a good workaround. It "steals" space from the other windows inside the frame. Where Speedbar instead provides a separate frame on the side of the existing one. I realize this only works in a graphical setup, but maybe treemacs would be able to check for that and, possibly also given a customization, provide the "speedbar" layout if not inside terminal? Just a thought. interested to hear your thoughs. Are there principles that prohibits this? And what would be the suggested workaround if you can think of one?

Screenshots to illustrate my point:
Let's say I'm having emacs open and it looks like this:
![image](https://user-images.githubusercontent.com/1709034/91632014-33d79780-e9de-11ea-9d2b-f581e4b3daaa.png)

Opening treemacs leaves me with this: (leaving the other windows with very little space left)
![image](https://user-images.githubusercontent.com/1709034/91632022-4782fe00-e9de-11ea-86b4-186dc7d2b06f.png)

And to compare, speedbar does this: (leaving the original frame and windows as is)
![image](https://user-images.githubusercontent.com/1709034/91632043-6bdeda80-e9de-11ea-9fdd-24ea745c34d8.png)

**Comment by Alexander-Miller** [comment]
Sorry, but I'll have to pass. Using another frame

 - makes Alt-Tab useless
 - won't work with a tiling window manager, so I won't even be able to test it
 - would be a lot more complicated than just fiddling around with frame sizes since by default treemacs buffers are localized to frames and it'd be very tedious and messy to work around that.

There is also no reason for treemacs to need more space than speedbar does. Quite the opposite - speedbar's extra frame might have border decorations and needs some distance between itself and the main frame - space that treemacs does not need.

Treemacs is wider in your screenshots, but that's what `treemacs-width` and `treemacs-set-width` are for.

It looks like your Emacs isn't fullscreen. That's the only scenario where it would look like speedbar needs less space since it leaves the original frame as is. If that's how you do it I guess you can change your frame size based on whether treemacs is visible or not. That means hooking into `treemacs-select-hook`, `treemacs-quit-hook` and `treemacs-kill-hook` with a call like `(set-frame-width (selected-frame) 100)`.

**Comment by Whil-** [comment]
Okay, understood. What you mention makes very much sense. Would it be feasible at some point to provide a customization that would make treemacs expand the width of the existing frame, as a way to solve the issue I'm having? If in a graphical environment that is, and maybe if below a certain width-threshold...

Any how - Consider it a feature request =) Or possibly a future pull request, if you don't see any immediate issue with including it.

Thanks
/G

**Comment by Alexander-Miller** [comment]
To be honest I'd rather not include features where the number of users is unlikely to exceed 1 and imitating speedbar's behavior when emacs is not in fullscreen mode seems to be such a rare and special case. So let's instead see if I can't help you set up what you want in your own config. Treemacs should have enough hook options to make it happen.

Here's a start:

```Elisp
(add-to-list 'treemacs-select-hook #'frame-size-adjust)

(defun frame-size-adjust ()
  (unless (<= 850 (frame-pixel-width))
    (let* ((treemacs-width (window-width (treemacs-get-local-window) :pixelwise))
           (frame (selected-frame))
           (frame-pos (frame-position frame)))
      (set-frame-width frame (+ (frame-pixel-width) treemacs-width) nil :pixelweise)
      (set-frame-position frame (- (car frame-pos) treemacs-width) (cdr frame-pos)))))
```

That'll enlarge the left side of the frame by the width of the treemacs window. The 850 can be moved to a variable or calculated dynamically.

There's also #552 to consider. The discussion in that ticket went nowhere, but I do intend to see it through.

**Comment by Whil-** [comment]
Thanks, @Alexander-Miller. Understood and I'll have a look at implementing that in my personal init. Cheers!
