### ISSUE TITLE
Remove treemacs-elisp-imenu-expression?

### ISSUE THREAD

**Issue by minad** [Alexander-Miller/treemacs#737]
I don't think treemacs should overwrite the imenu-generic-expression variable, since it might be modified at other places. Furthermore this variable is pretty much unrelated to treemacs and this leads to confusion (I found the overwrite using the variable watcher). We also don't have an override for all the other programming languages... I would suggest removing this customization option, maybe adding a note to the readme.

Besides that treemacs works great - much more solid now, than when I tried it the first time! Thank you very much!

**Comment by Alexander-Miller** [comment]
> I don't think treemacs should overwrite the imenu-generic-expression variable, since it might be modified at other places. 

So do I. I have no idea what I was thinking making it overwrite a buffer's default value. The plan was for it to only apply to treemacs' own tag queries - I wanted more informative tag groups than just 20 variables and 60 functions covering the entire screen.

So yeah, I think removing it is one step too far, but the override definitely needs to go.

**Comment by minad** [comment]
I mean it looks nice - it would be great to have it in the docs here as a suggestion! And I will certainly use it to tweak the elisp config, but its just the wrong layer! I can make a PR if you want.

**Comment by Alexander-Miller** [comment]
> but its just the wrong layer!

It's in the tags layer, and all it's good for since the patch I just pushed is deciding how treemacs groups elisp buffers' tags. I don't see how it's in the wrong place.

The PR is not necessary anymore, I would have gone along with the removal anyway - the custom imenu expression does serve the important purpose of uncluttering the tags menu.

You can also set the variable to nil now to make treemacs use the default imenu expression.
