### ISSUE TITLE
Compilation warnings

### ISSUE THREAD

**Issue by seagle0128** [Alexander-Miller/treemacs#742]
- GNU Emacs 28
- macOS Catalina
- the latest treemacs

```elisp
Warning (comp): [Treemacs] Warning: couldn't find hl-line-mode's background color for icons, falling back on unspecified-bg.
```

**Comment by Alexander-Miller** [comment]
That warning is printed (also at load time) when treemacs cannot determine hl-line-mode's background color. If that also happens when treemacs is actually loaded for use selected icons' background color may not align probably with the hl-line overlay.

So depending on whether everything else works you may choose to either:
 - ignore it
 - bind the variable `treemacs-no-load-time-warnings`  so the warning is no longer printed
 - Change/expand your theme/config so the face is available when needed by treemacs

The really interesting part it that it's falling back on `unspecified-bg`. That should not happen, treemacsis supposed to select a static fallback if the face is not specified. What does the following code return for you:

```Elisp
(pcase (face-attribute 'default :background nil t)
      ('unspecified
       (prog1 "#2d2d31"
         (unless (boundp 'treemacs-no-load-time-warnings)
           (message "[Treemacs] Warning: coudn't find default background colour for icons, falling back on #2d2d31."))))
      ('unspecified-bg
       (prog1 "#2d2d31"
         (unless (boundp 'treemacs-no-load-time-warnings)
           (message "[Treemacs] Warning: background colour is unspecified, icons will likely look wrong. Falling back on #2d2d31."))))
      (other other))
```

**Comment by seagle0128** [comment]
Thanks for the quick reply!

The result of the snippet above is `"#21242b"` .

**Comment by nesteiner** [comment]
@Alexander-Miller hey, there is a similar warning always showing on start up emacs 
`[Treemacs] Warning: coudn’t find default background colour for icons, falling back on #2d2d31.`  
what is the reason ??

**Comment by Alexander-Miller** [comment]
It means your theme does not define a background color for the `default` face, which treemacs needs for its icons. There's more info and fixes in the FAQ.
