### ISSUE TITLE
Rename dialogue in small buffer instead of minibuffer

### ISSUE THREAD

**Issue by m4xxed** [Alexander-Miller/treemacs#763]
For some reason, after my last update, the Rename dialogue in treemacs appears directly in the treemacs buffer below the file to rename, instead of the usual minibuffer renaming dialogue. 

This irritates me, as the cursor is not visible and editing filenames became a weird guessing game.

I couldn't find any configuration option within emacs for that type of behaviour and also not mentions of a change in the last commits. 

I'd be happy about a hint as to where I can configure that behaviour.

**Comment by m4xxed** [comment]
Nevermind, found your discussion and the cfrs-window. I like the idea, just can't really use it since cursor is not visible at all in my case. But I like it, and I found how to turn it off (change treemacs-read-string-input variable)

Love this project, keep up the good work!

**Comment by Alexander-Miller** [comment]
> just can't really use it since cursor is not visible at all in my case.

That is actually a bug. Turns out posframe hides the cursor, but I never noticed because evil-mode's cursor-handling take priority over posframe's hiding. I have pushed  a patch to address that now.

Doing something like `(set-face-background 'internal-border "#669966")` so you have a visible border would also help.
