### ISSUE TITLE
No Git-related face updates when performing Magit hard reset or discard

### ISSUE THREAD

**Issue by mentalblock** [Alexander-Miller/treemacs#768]
Thank you for your work on treemacs, I am finding it makes me more productive.

When I make changes to a file and it gets correctly highlighted with the modified face by treemacs using the 'deferred strategy for treemacs-git-mode. Unfortunately, if I open up  Magit and I hit `k` (discard) or `X h` (hard reset), I expect the "unstaged" face of the file in the treemacs view to return to the normal face but this does not happen. The file buffer of the modified file gets reverted automatically by Emacs as usual, but the treemacs view does not reflect that. I must force refresh the tree view in order to get the face to return back to normal.

As for my platform, I am running Emacs 27.1, treemacs 2.8, along with treemacs-magit, and treemacs-projectile. 

Please let me know if there is something I may be doing incorrectly or if you need any more information. Thanks.

**Comment by mentalblock** [comment]
To clarify, I expected the same filewatch-mode mechanism that detected the initial unstaged changes to also detect that the modified file was again reverted back via the discard or hard reset. This did not happen.

**Comment by Alexander-Miller** [comment]
Changes made by git can be a bit chaotic. From treemacs' pov resetting a file means that it is first deleted, then created, then modified, in that order (at least that's what happens on my system). Treemacs only remembers the last most relevant event. For this case it's the create event since modifications are only needed for updating a file's git status, and creating a new file will do that anyway.

Fortunately fixing that should be simple enough, just have to update a file's git status when it is "created", but already exists in treemacs.
