### ISSUE TITLE
Make recentf ignore cache file treemacs-persist

### ISSUE THREAD

**Issue by jcs090218** [Alexander-Miller/treemacs#777]
I don't know if this should be fixed by this package or not. I think it's quite annoying seeing file `~/.emacs.d/.cache/treemacs-persist` in my recent file list.

**Comment by Alexander-Miller** [comment]
That's definitely for treemacs to fix. Patch is be dropped shortly.

**Comment by eutro** [comment]
This doesn't seem to work any more since `recentf-filename-handlers` now contains `abbreviate-file-name` by default since [about two years ago](https://lists.gnu.org/archive/html/bug-gnu-emacs/2022-06/msg01484.html).

The current solution is fragile to several things such as:

- `recentf-filename-handlers` making the file name not be the absolute one (as is currently the default)
- customization of `treemacs-persist-file` after load (which Treemacs is fragile to anyway)
- the file path of `treemacs-persist-file` being interpreted as a regular expression, which may lead to weird behaviour

I'd suggest adding a predicate to the list instead, such as
```emacs-lisp
(with-eval-after-load 'recentf
  (defun tremacs--persist-file-p (file)
    "Return non-nil if FILE is one Treemacs' persistent files."
    (or (file-equal-p file treemacs-persist-file)
        (file-equal-p file treemacs-last-error-persist-file)))
  (declare-function tremacs--persist-file-p "treemacs-compatibility")

  (with-no-warnings
    (add-to-list 'recentf-exclude #'tremacs--persist-file-p)))
```
which should make it robust to pretty much any kind of path that `find-file` supports.
