### ISSUE TITLE
Feature request: collapse `node_modules` and `.venv` on exit (when Treemacs buffer is not focused)

### ISSUE THREAD

**Issue by Invertisment** [Alexander-Miller/treemacs#807]
While it's useful to browse those directories from time to time I mostly jump to them occasionally and don't search inside of them in the Treemacs buffer. And if I do search in Treemacs buffer then it's focused.

I think it would be a good idea to have a variable that looks something like this (purely a suggestion at this point):

```
(setq auto-collapsed-parent-dirs '("node_modules" ".venv"))
```

I use Spacemacs and sometimes I jump to sources of some libraries. Let's say I'm in a TypeScript project that has `node_modules` directory. If I jump to some library then it results in expanded `node_modules` and Treemacs buffer becomes too large to understand what's going on in there. The system handles it fine, it's just me that I don't want to know where I was jumping before.

Example:
I have an `App.jsx` file that uses a library. Let's say it has a line `import "bigdecimal"`.
I jump to that line. Treemacs buffer detects that I'm in a different source file and opens up `node_modules` directory. This is great because I can browse other sources now.
Then I press `C-o` and jump back to my `App.jsx`. Treemacs buffer detects that and focuses `App.jsx` line of the buffer. Great, I know what's going on.
Now I'd like to find a new buffer in Treemacs, let's say even in a different project. Here I have a problem that my Treemacs buffer is filled with `node_modules` packages. And there is always a lot of those.

I'd like to reduce this problem by auto-collapsing specific parent directory when Treemacs buffer is not focused. In this case it would be `node_modules`.

**Comment by Alexander-Miller** [comment]
I get where you're coming from, but features that involve doing things when windows are (de-)selected are rather unpleasant to implement, and the performance could get troublesome as well since there could be a lot of files to check for closing whenever you deselect treemacs. 

So how about a no-follow list instead?  You'd be able to tell treemacs to not automatically go into anything that looks like /node_modules/ and if you want to see the directory anyway you can use `treemacs-find-file` manually. Plus the option to only apply the no-follow if the offending directory is not expanded already.

**Comment by Invertisment** [comment]
It would fix the size of the buffer but then if I'd want to browse the contents of `node_modules` I may need to open the Treemacs buffer. Is there a command that focuses the current file? I think this could be fine.

**Comment by Invertisment** [comment]
It says that there is a shortcut that focuses the current file in Treemacs buffer:
https://develop.spacemacs.org/layers/+filetree/treemacs/README.html#global
`SPC f T`.

How would it work for collapsed directory if it wouldn't be expanded? I think it's a good idea to expand it. But then collapse it on exit from the treemacs buffer. 

Or alternatively there could simply be a keybind that collapses specific directories if buffer gets too clogged up. It could be activated on lost focus. Not sure.

**Comment by Alexander-Miller** [comment]
> How would it work for collapsed directory if it wouldn't be expanded?

Blacklisted directories would not be expanded *automatically*, when you just happen to look at some library code. You'd still be able to get in there yourself, either by just TABbing things open, or using `SPC f T`

> Or alternatively there could simply be a keybind that collapses specific directories if buffer gets too clogged up. It could be activated on lost focus. Not sure.

I've come up with a plan now. It goes like this:

 - 1 blacklist for directories follow-mode will ignore. Manually entering them still works.
 - 1 cleanup list for directories to close all at once
 - An interactive command to close everything on the cleanup list
 - A hook that runs whenever treemacs loses focus

You'll be able to combine points 3 & 4 to get your desired results. I won't make it happen by default because even a small delay whenever treemacs is unselected is enough to make using it thoroughly unpleasant. but using a hook will be trivial.

(There is also already some general cleanup in the form of `treemacs-collapse-project/-all-projects/-other-projects`.)

**Comment by Invertisment** [comment]
I think the first case would be more than enough. Others would have perfect but diminishing returns.
Also I'm already somewhat used to live with the original behavior and it didn't receive likes so I'm not sure what other users think about it. Probably it's fine to put this one somewhere in the back of the backlog.
Thank you very much. :))

**Comment by Alexander-Miller** [comment]
Let's see how it goes: I've now added `treemacs-cleanup-litter`, bound to `C` that handles the cleanup for you.  You might have to adjust `treemacs-litter-directories` to your use-case.

**Comment by dmvianna** [comment]
> blacklist for directories follow-mode will ignore. Manually entering them still works.

Was this implemented? That would be great to use with `node_modules`, `.venv` and similar while browsing from **eglot** or **lsp-mode**.

**Comment by Alexander-Miller** [comment]
Bit later than planned, but it's pushed now. See `treemacs-follow-ignore-functions`.

**Comment by dmvianna** [comment]
> Bit later than planned, but it's pushed now. See `treemacs-follow-ignore-functions`.

You mean `treemacs-file-follow-ignore-function`, right? Thank you!

**Comment by dmvianna** [comment]
I accept suggestions on how to make it more idiomatic, but this works:

```elisp
(defun ignore-packages (path patterns)
     "Return non-nil if PATH contain any of the PATTERNS."
     (let* ((path-parts
             (split-string
              (file-name-directory (expand-file-name path)) "/" t))
            (matches
             (cl-loop for elt in patterns
                      collect
                      (cl-remove-if-not
                       (lambda (x) (string-equal elt x)) path-parts))))
       (remove nil matches)))

(use-package treemacs
  :custom
  (treemacs-file-follow-ignore-functions
   '((lambda (path) (ignore-packages path '(".venv" "node_modules" ".metals"))))))
```
