### ISSUE TITLE
After enabling treemacs, helm commands takes the whole window.

### ISSUE THREAD

**Issue by introom** [Alexander-Miller/treemacs#808]
After enabling treemacs, helm commands takes the whole window.

When treemacs is enabled but helm command is not invoked:
![image](https://user-images.githubusercontent.com/669045/116780104-eb143900-aaac-11eb-9dea-0d8de468a985.png)

However, when Helm-M-x is enabled:

![image](https://user-images.githubusercontent.com/669045/116780109-f8c9be80-aaac-11eb-9334-d7eb4ad2e4c4.png)

The expected behavior is that, the helm command shoudl take a small portion of the window, for example,
This is what happened when treemacs is disabled:
![image](https://user-images.githubusercontent.com/669045/116780132-1860e700-aaad-11eb-93e3-c66549f89c06.png)

**Comment by Alexander-Miller** [comment]
Treemacs does not do anything special to display itself, you'll see the same behavior with `(display-buffer-in-side-window (current-buffer) '((side . left)))` because helm isn't great at dealing with side-windows.

Setting `treemacs-display-in-side-window` to nil might help, if it does not you need to teach helm how to behave consistently. shackle is probably the easiest way to do the latter: https://github.com/wasamasa/shackle

**Comment by introom** [comment]
Thanks. Setting `helm-split-window-in-side-p` to `t` solves the problem.
