### ISSUE TITLE
evil-window-left does not work with treemacs

### ISSUE THREAD

**Issue by introom** [Alexander-Miller/treemacs#809]
Call evil-window-left from the right window:
![image](https://user-images.githubusercontent.com/669045/117678778-4ac3c000-b1e2-11eb-99d4-00ce2b6be2ec.png)

It errs with: 

![image](https://user-images.githubusercontent.com/669045/117678832-57481880-b1e2-11eb-89b2-0096d29a3612.png)

**Comment by Alexander-Miller** [comment]
If evil cannot find treemacs then that is a problem with evil or just your Emacs version, since all evil does is wrap `windmove-left`. Treemacs does not do anything special to display itself, by default it's a simple `display-buffer-in-side-window` call, you'll have the same problem with just `(display-buffer-in-side-window (current-buffer) '((side . left)))`.

I can't reproduce the problem either, evil can switch back and forth just fine on my end, at least on my very recent self-compiled version of Emacs 28. So if side-windows are indeed to blame you can set `treemacs-display-in-side-window` to nil so it doesn't use side-windows anymore.

If that doesn't help you'll have to try and use a newer Emacs, or at least a newer windmove.el, whichever is easier.

**Comment by introom** [comment]
This should be related to this issue:https://github.com/Alexander-Miller/treemacs/issues/610
