### ISSUE TITLE
Treemacs faces not applied

### ISSUE THREAD

**Issue by jbharat** [Alexander-Miller/treemacs#81]
Treemacs faces not applied.  I checked the treemacs-faces. They seem to fine. 

Mac, spacemacs develop
treemacs-20171016.956
treemacs-evil-20170925.2232
treemacs-projectile-20170903.1235

layer config
```
     (treemacs :variables
               treemacs-use-filewatch-mode t
               treemacs-use-follow-mode t
               treemacs-use-collapsed-directories 3
               )
```

![screen shot 2017-10-17 at 5 52 41 pm](https://user-images.githubusercontent.com/6837979/31650671-2f4062aa-b364-11e7-94a3-4e0a8d6f7554.png)

![screen shot 2017-10-17 at 5 55 32 pm](https://user-images.githubusercontent.com/6837979/31650737-6f2cbe7c-b364-11e7-95e9-ce44106d419e.png)

**Comment by Alexander-Miller** [comment]
* Do all nodes (files, dirs & tags) have the same face?

 * Is it the default face for buttons?

 * Is the correct face applied after you do a refresh?

**Comment by jbharat** [comment]
This is the only face that is getting applied. Same face to everything except header. I deleted treemacs from elpa folder and tried. Same result.

**Comment by Alexander-Miller** [comment]
Not that kind of refresh. I mean the one bound to r.

**Comment by jbharat** [comment]
I didn't try that. I will test tomorrow.

**Comment by Alexander-Miller** [comment]
Assuming the answer is yes: [It's a known bug in emacs](https://debbugs.gnu.org/cgi/bugreport.cgi?bug=28599). The most likely cause is an old version of swiper, so updating that should fix things. If its not swiper its some other package calling `font-lock-ensure` and youll need to find the culprit by grepping your elpa dir

**Comment by jbharat** [comment]
I tested on Ubuntu. It works perfectly. So I am having this issue on Mac. I will check again today.

**Comment by jbharat** [comment]
I checked on mac again. It is odd as both mac and ubuntu use the same config. So I don't think it is an issue with packages. Swiper is latest. And grep search for `font-lock-ensure` resulted in following packages
`git-commit, hl-todo, hy-mode, markdown-mode, org-plus-contrib, package-lint, swiper, typescript-mode, web-mode` 

I think we can close this issue

**Comment by jbharat** [comment]
I took a fresh download of spacemacs .emacs.d develop branch on ubuntu as well. Now I have the same issue on ubuntu. Something changed in spacemacs develop which is causing it.

**Comment by Alexander-Miller** [comment]
I dont think it's just spacemacs since I have no such problem. We're not even fully clear that it's the font-lock-ensure that's to blame. Do you answer yes to all 3 questions I listed above? In addition does it only happen once, do the colors stay as they should be after a refresh, unless you run `treemacs` again?

You can try the following fix, it'll work it `font-lock-ensure` is to blame.
```
(add-hook 'treemacs-mode-hook 
          (lambda () 
            (setq-local font-lock-ensure-function #'ignore)
            (setq-local font-lock-fontify-buffer-function #'ignore)))
```

**Comment by jbharat** [comment]
Do all nodes (files, dirs & tags) have the same face? `Yes`
Is it the default face for buttons? `Yes`
Is the correct face applied after you do a refresh? `No`

Above hook for font-lock-ensure didn't fix it.

**Comment by Alexander-Miller** [comment]
In this case this bug is not something I've seen before and you'll need to go dig into your config to try and find the cause. Start off with loading treemacs into `emacs -q`, then just bare spacemacs, without any layers and your personal config, then start enabling layers one by one. 
If we're lucky we can pin this down to a single layer or setting.

More questions:
 * Do the faces start out misaligned or do they change afterwards?
 * What face are the buttons actually fontified with? You can use `SPC h d c` to grab the info for char at point. Treemacs' cursor is hidden by default, but I use a consistent scheme to dodge images - just hit <right> a couple of times and you'll be on a button. The character's text properties will be listed on the bottom.

**Comment by jbharat** [comment]
Sorry and thanks for guiding me in the right direction. It is caused by below code in my config
```
(define-globalized-minor-mode my/rainbow-mode rainbow-mode
  (lambda () (rainbow-mode 1))
  )
(my/rainbow-mode 1)
```

I wanted colors to be shown on all hex color codes. I will try to fix it. Thanks again
