### ISSUE TITLE
treemacs-20210524.1338 out of range

### ISSUE THREAD

**Issue by anpt** [Alexander-Miller/treemacs#817]
Problem to open workspace, projects get Args out of range: #s(treemacs-project "test" "/home/test" local-readable), 4

**Comment by Alexander-Miller** [comment]
Enable `debug-on-error` and show me the stack trace.

**Comment by Alexander-Miller** [comment]
That's no it. Normally Emacs should pop up a \*Backtrace\* buffer. That's what I need to see. Otherwise it's all guesswork on my end.

When exactly does the bug happen, what command do you use?

**Comment by anpt** [comment]
treemacs-finish-edit

**Comment by Alexander-Miller** [comment]
Did you restart since you updated treemacs?

A project should look like this `#s(treemacs-project "Treemacs" "/home/am/Documents/git/treemacs" local-readable nil)` - there should be a 4th property.  It was added back in december 2020. If you haven't updated since then, and haven't restart when you did it might explain the error.

**Comment by anpt** [comment]
I removed treemacs package and delete the folder in .emacs.d. Then i installed the package again and now it work perfect!
