### ISSUE TITLE
Resize or Split treemacs window?

### ISSUE THREAD

**Issue by qohelet** [Alexander-Miller/treemacs#825]
I use the plain emacs 26.3 and just switched from Neotree to Treemacs.
I'm curious if it is possible to split or resize the treemacs window?

On resizing I get the error:
`No resizable window on the left of this one`
On splitting:
`Cannot split side window or parent of side window`

Also it is not possible to lower the font size until a certain degree.

Can someone help me?
Thank you

**Comment by Alexander-Miller** [comment]
>  Cannot split side window or parent of side window

By default treemacs is displayed in a [side-window](https://www.gnu.org/software/emacs/manual/html_node/elisp/Side-Windows.html). If you don't want that behavior you can set `treemacs-display-in-side-window` to nil.

>  No resizable window on the left of this one

Treemacs has a fixed window width by default so adding or deleting windows or commands like `balance-windows` don't affect treemacs' size. 

You can use
 - `treemacs-toggle-fixed-width`, bound to `tw`, to unlock the width, or
 - `treemacs-set-width`, bound to `w`, to choose a new width, or reset it to the default with a prefix arg if it's been unlocked

> Also it is not possible to lower the font size until a certain degree.

Treemacs does not touch fonts. At most you can change every `treemacs-*` face to have a smaller size. Just using `treemacs-resize-icons` may also be enough since the icons might be larger than your characters.

**Comment by qohelet** [comment]
I used 

```
(use-package treemacs
  :ensure t
  :defer t
  :init
  (with-eval-after-load 'winum
    (define-key winum-keymap (kbd "<f8> SPC") #'treemacs-select-window))
  :config
  (progn
    (setq treemacs-collapse-dirs                 (if treemacs-python-executable 3 0)
          treemacs-deferred-git-apply-delay      0.5
          treemacs-directory-name-transformer    #'identity
          treemacs-display-in-side-window        nil
          ...
          treemacs-toggle-fixed-width            tw
          ...
```

The rest from the default configuration and get:



`Error (use-package): treemacs/:config: Symbol’s value as variable is void: tw`

**Comment by Alexander-Miller** [comment]
> Symbol’s value as variable is void: tw

I was talking about keybinds. `tw` are the keys you're supposed to press (you may want to try `?` for the helpful hydra that'll show your everything).

As a matter of fact there is no simple way to set the global default. The toggle only ever affects the local treemacs buffer (and you can have multiple at the same time), so the best you can do is add it to treemacs-mode-hook. 

But I do think that this is a reasonable thing to want, so give me a few days and I'll add a proper configuration option that you can use.

**Comment by qohelet** [comment]
@Alexander-Miller- I'm mostly using emacs for Python and would like to have a buffer where I'm listing the functions of the current buffer. 
Thank you :)

**Comment by Alexander-Miller** [comment]
You can control the width with `treemacs-width-is-initially-locked` now.

> I'm mostly using emacs for Python and would like to have a buffer where I'm listing the functions of the current buffer.

Treemacs can show tags, just keep expanding the files. You'll have to hit the icon if you are using the mouse, otherwise you just open the file. The tags are the same as those from imenu, so if imenu does not show tags like you want then neither will treemacs. The imenu-list package is also an option.
