### ISSUE TITLE
Single Click not working?

### ISSUE THREAD

**Issue by qohelet** [Alexander-Miller/treemacs#826]
I use treemacs in emacs 26.3 and added the additional line for the single click:

https://github.com/Alexander-Miller/treemacs#mouse-interface
`(define-key treemacs-mode-map [mouse-1] #'treemacs-single-click-expand-action)`

```
Debugger entered--Lisp error: (void-variable treemacs-mode-map)
  (define-key treemacs-mode-map [mouse-1] (function treemacs-single-click-expand-action))
  eval-buffer(#<buffer  *load*-660690> nil "/home/marioschwaiger/.emacs.d/IDE.el" nil t)  ; Reading at buffer position 17175
  load-with-code-conversion("/home/marioschwaiger/.emacs.d/IDE.el" "/home/marioschwaiger/.emacs.d/IDE.el" nil nil)
  load("~/.emacs.d/IDE.el")
  eval-buffer(#<buffer  *load*> nil "/home/marioschwaiger/.emacs" nil t)  ; Reading at buffer position 87
  load-with-code-conversion("/home/marioschwaiger/.emacs" "/home/marioschwaiger/.emacs" t t)
  load("~/.emacs" t t)
  #f(compiled-function () #<bytecode 0x1e0f4d>)()
  command-line()
  normal-top-level()
```

When using the command `treemacs-single-click-expand-action` I get the error:
`command-execute: treemacs-single-click-expand-action must be bound to an event with parameter`

**Comment by Alexander-Miller** [comment]
You need lazy-loading. The variable is void because treemacs has not yet been loaded. This is the second time that this has come up, so I've adjusted the example accordingly. The code has to look like this:

```Elisp
(with-eval-after-load 'treemacs
    (define-key treemacs-mode-map [mouse-1] #'treemacs-single-click-expand-action))
```

> When using the command treemacs-single-click-expand-action I get the error:
command-execute: treemacs-single-click-expand-action must be bound to an event with parameter

That message comes from Emacs itself, so that's working as intended. The command needs a mouse-click event, otherwise it won't work.
