### ISSUE TITLE
treemacs should always switch to the root of current project instead of the directory of current buffer file when enable treemacs-project-follow-mode.

### ISSUE THREAD

**Issue by zw963** [Alexander-Miller/treemacs#838]
Or, can we offer a custom variable, to controller this behavior ? thank you.

**Comment by Alexander-Miller** [comment]
I am not sure I understand what you mean - and when trying to reproduce the question I've run into a bug that I need to fix first. Can you give me an example for this behavior?

**Comment by zw963** [comment]
## reproduce

### 1. i enable project like this

```cl
(require 'treemacs-project-follow-mode)
(treemacs-project-follow-mode t)
```

### 2. then i open my project. assume is `~/Stocks/marketbet_crawler`, and then open treemacs

it works as expected, treemacs will use `~/Stocks/marketbet_crawler` as root

![image](https://user-images.githubusercontent.com/549126/132449410-124787a2-bd8d-4079-8c32-7e7d2fb0b03f.png)


### 3.  Then i open `~/Stocks/marketbet_crawler/app/app.rb`, treemacs change root to `~/Stocks/marketbet_crawler/app`, like this.

![image](https://user-images.githubusercontent.com/549126/132449708-29979c7e-3a4b-453b-9cc1-0b846505995f.png)


## What i expected

treemacs should not change root to app folder, instead, it should keep original root, but, app subfolder be expanded.

like this.

![image](https://user-images.githubusercontent.com/549126/132450042-4ab08806-b3f7-4b5f-a02b-e734e3dd91c9.png)

**Comment by Alexander-Miller** [comment]
The bugs I ran into are fixed now. As for your issue, that part is actually working as intended. The behavior you want is for treemacs to *not* project-follow  because the app.rb file is in the marketbet_crawler project already. 

However I explicitly made treemacs do just that after I managed to make it follow into my home directory as the current project. Since every single other file I could reasonably open is stored in the home directory there was no way for treemacs to follow into an  actual project without manual intervention. So I figured it'd be better for treemacs to be precise to avoid getting stuck too high up in the file hierarchy.

The reason that treemacs follows you into a sub-directory in your case is because it does not know that the marketbet_crawler directory is the root of a project. Treemacs tries asking both projectile (if installed) and the builtin project.el for the current project root. Only when both fail does it fall back to the current directory.

So what you should do is make your project known to Emacs, either by putting it under version control, or adding an empty ".projectile" file to the root directory.

**Comment by zw963** [comment]
> So what you should do is make your project known to Emacs, either by putting it under version control, or adding an empty ".projectile" file to the root directory.

Okay, so, the issue is, my project was under version controller, but, i neither use `projectie` , nor `project.el` or `magit`.

because after i open a buffer in  marketbet_crawler project,  when i moving my cursor in buffer, it change current folder as root automatically, i consider this is not correct, because project title/path  has been updated to that sub-folder when i run  `treemacs-edit-workspaces` to check it.

**Comment by zw963** [comment]
Wired, even i create a new empty `.projectile`, and restart emacs daemon from current marketbet_crawler project root, then, after i open current project use direct, and try open `app/app.rb`, it change root to app/ again.

![image](https://user-images.githubusercontent.com/549126/133034589-c741f611-a3bd-47bc-8e44-44e146894893.png)

**Comment by Alexander-Miller** [comment]
Let's keep this open.

**Comment by embeddedpenguin** [comment]
I'm using doom emacs w/treemacs and projectile. I have disabled treemacs follow mode and treemacs project follow mode. For some reason, the treemacs root keeps changing depending on whichever file I am in, just like OP.
For example:
```
A/
.git
example.txt
    B/
    .git
    example.txt
```

I open project A and open example.txt and treemacs opens A as it should. If I then open example.txt in folder B, it automatically shoves the root down to B. I then try navigating back to A/example.txt, and it can't move the root back up to A:
`[Treemacs] Project 'B' is included in '/home/user/Projects/A. Projects may not overlap.`

**Comment by embeddedpenguin** [comment]
Actually it turns out toggling the values for treemacs-project-follow-mode and treemacs-follow-mode during use didn't actually toggle the functionality. Restarting my emacs solved it. However, disabling these features leaves me in a predicament:

Scenario:
open emacs
projectile open a known project
open treemacs, it sets the root to my home directory by default, every time i add a project that isn't currently in a workspace

Using the follow modes treemacs provides solves this issue, but it creates another one. 
Scenario 2:
open emacs
open a known projectile project
open treemacs and it sets the root to the proper directory
navigate to subproject
treemacs resets the root to the subproject
navigate back up
doesnt reset root to parent project, throws error seen above

So I'm kinda stuck between manually creating a workspace so treemacs knows what the root is, since treemacs doesn't use projectile as the root project, **or** I can change the root in my workspace every time I navigate from a subproject to the parent project. Both of these solutions are a little wonky.

**Comment by zw963** [comment]
Oops, i don't know this issue is auto-closed, is this feature was fixed? ping @Alexander-Miller

**Comment by embeddedpenguin** [comment]
> Oops, i don't know this issue is auto-closed, is this feature was fixed? ping @Alexander-Miller

I can make a new issue if I need to. It's essentially the same problem OP had though, as far as I can tell.

**Comment by Alexander-Miller** [comment]
> I can make a new issue if I need to.

Let's reopen.

>  open treemacs, it sets the root to my home directory by default, every time i add a project that isn't currently in a workspace

What does your config look like? Does it also happen without doom? How do you add projects exactly?

> Actually it turns out toggling the values for treemacs-project-follow-mode and treemacs-follow-mode during use didn't actually toggle the functionality

That sounds suspicious to me. Did you just set the variable values, or did you actually disable the minor mods - as in `(setf treemacs-follow-mode nil)` vs `(treemacs-follow-mode -1)`?

**Comment by zw963** [comment]
Hi, my original issue get fixed after test just now, thank you very much!
