### ISSUE TITLE
Would be nice to be able to switch workspaces from elisp rather than doing the prompt in the minibuffer

### ISSUE THREAD

**Issue by flajann2** [Alexander-Miller/treemacs#839]
And I think all  commands with the mini buffer interaction should have an option of passing the parameters to them programmatically, but  that might be a tall call to do on something like this.  But it would be a nice to have so that I can better integrate your framework into my own. :)

**Comment by flajann2** [comment]
I looked into your code and found **treemacs-do-switch-workspace**. Is this considered undocumented? But it does what I want.

**Comment by Alexander-Miller** [comment]
>  Is this considered undocumented? But it does what I want.

Because it is not mentioned in the readme? No, I just never bothered with a list of all the public api functions. I plan to document the api from #788, so that'll be a good to place to also describe at least the important stuff.

I do take the whole convention of using a single dash for public api seriously, so if you see a single-dash-function like this you can safely assume that it is meant to be publicly used and will remain stable, barring major rewrites. Renames do happen, but the old name is kept at least for months, and your compiler will give you a deprecation warning.

The "foo" and "do-foo" naming convention is something that's grown in treemacs because I often needed 2 versions of a function, one with all the bells and whistles, and another to just get the thing done and nothing else. For projects and workspaces that means interactive and programmatic removal and addition, but there's also pairs like`treemacs-delete-single-node` and `treemacs-do-delete-single-node` which are identical except the former also uses `treemacs-save-position`.

**Comment by flajann2** [comment]
Thanks for your response. And please keep up the good work. I no longer use ECB because it does not seem to be maintained at all, and is a big buggy. Treemacs works much better, so I use it all the time now.  And it melds nicely with Evil. :)

**Comment by flajann2** [comment]
I also love how it does icons for the different filetypes. That helps out a lot!!!!
