### ISSUE TITLE
Error running hook "treemacs--follow-project" while splitting windows

### ISSUE THREAD

**Issue by dankeyy** [Alexander-Miller/treemacs#875]
While trying to split any window with treemacs follow mode enabled, I get this error:
```Error (window-selection-change-functions): Error running hook "treemacs--follow-project" because: (wrong-number-of-arguments (1 . 1) 0)```

**Comment by Alexander-Miller** [comment]
If I am reading the message correctly the hook failed because `treemacs--follow-project` expects 1 argument, but was given zero. I made it take 1 ignored argument because that is what the spec of `window-selection-change-functions` says is needed:

```
Functions called during redisplay when the selected window has changed.

The value should be a list of functions that take one argument.
```

I also cannot reproduce the problem, splitting windows works just fine on my end.

What does the eldoc of `window-selection-change-functions` say on your end, and what version of Emacs are you on?
