### ISSUE TITLE
Allow sub-projects under a given project

### ISSUE THREAD

**Issue by frgomes** [Alexander-Miller/treemacs#878]
First of all: Thank you so much for Treemacs. It is absolutely great and brings so many benefits for users.

From READ.ME:
> Another restriction is that the same part of the file system may not appear more than once as part of the workspace. For example it is not possible to have both /Documents and /Documents/ProjectX as projects in the same workspace, since internally treemacs heavily relies on every node having a unique natural key in its absolute path.

I find this restriction inconvenient. If I'm creating a multi project structure from scratch, I could possibly find creative ways for circumventing this restriction. However, not always we have such freedom when we face a legacy codebase which needs to stick to enterprise/corporative practices or restrictions.

I'm not in the position of suggesting what/how Treemacs could possibly support this scenario, but I would be very happy if I could simply say that a sub-tree is a distinct project from the current project tree.

**Note**: maybe a duplicate of https://github.com/Alexander-Miller/treemacs/issues/489?

**Comment by Alexander-Miller** [comment]
This is _not_ a restriction that exists because it's how I think things _should_ be. It's really an inconvenient outgrowth of treemacs' gradual evolution towards being able to handle multiple file trees. I'd like to rid of it some day, however as it stands that would require a massive refactoring of everything and everywhere that would keep me busy for months, and I don't have that kind that time or energy while there's plenty of other open issues, some of which are years old. Sorry, but for now it'll have to say as it is.

There's 2 workarounds you can try:
 1. Use multiple workspaces in different frames
 2. Use just one single project that you navigate with `M-H` & `M-L`

**Comment by frgomes** [comment]
@Alexander-Miller : Thanks a lot for `treemacs` and thanks a lot for your help.

I would like to contribute to people landing here:

Turns out that the main difficulty I'm having is actually due to `projectile`, not `treemacs`, it seems.
I'm not plenty sure about the matter, since I haven't investigated deeply, but apparently `projectile` retrieves the home directory from the version control system of your choice. And so, despite that you can create multiple workspaces in `treemacs`, apparently (if I'm not mistaken!) this may not help at all since your project shown in `treemacs` is actually managed by projectile and, in this case, the root of your project is always the same, regardless how you organize projects `treemacs`.

It's not plenty clear to me how `projectile` discovers your `.git` folder somewhere else up in the directory tree, but it is not difficult to imagine that `projectile` may eventually just call `git` for that matter.

Another thing not clear to me: how people employing the "monorepo" workflow deals with that? In this case you could have lots different projects, employing several different programming languages, all under a single multi-project root.

So, this is my contribution, which adds more questions than answers.
