### ISSUE TITLE
Keybindings, discussion

### ISSUE THREAD

**Issue by quicknir** [Alexander-Miller/treemacs#89]
I had a couple of observations on the keybindings, at least as I observed them in spacemacs, and some thoughts. First, it's a bit surprising that M-j and M-k are used, even though C-j and C-k are free. Usually C- bindings are the first goto, and overall in vim style stuff in spacemacs you see C-j and C-k used more often and for more important functionality. Second, it would be nice if there was a way to do what tab does (whichc is one of the most important functionalities) without reaching to tab. And I also feel like it's a bit jarring that h and l, which are usually simple movement keys, shift the entire screen. So I was thinking along the files of having l open, and h close, and C-l and C-h to shift screens. Then, C-hjkl are the "more powerful" movement operations (shifting screens, or jumping neighbors), whereas hjkl are just moving up and down and opening/closing nodes. Maybe you considered all this and decided against, but just a thought (and I'd be curious to hear the reasoning).

**Comment by Alexander-Miller** [comment]
My reasoning? I more or less made shit up as I went along. The parts you're talking about are some of the earliest in treemacs. I did not really have a concrete plan then, wasn't even sure treemacs will even mature beyond the simple let's-see-what-I-can-even-do phase. All I had in mind was something evil-like and spacemacs-inspired. The current layout solidified as I added more features over time.

I can see where you're coming from, the scheme you propose definitely seems more cohesive. I'm only really against it because so large a change will annoy a lot of people and disrupt a lot of workflows.

IME keybinds are quite fickle and you can never please everyone. And if I do try I just end up with 3 different keybinds for refresh again. That's the kind of complexity I'm trying to avoid.

**Comment by wyuenho** [comment]
> Second, it would be nice if there was a way to do what tab does (whichc is one of the most important functionalities) without reaching to tab.

Yes! I [proposed](https://github.com/Alexander-Miller/treemacs/issues/79#issuecomment-352282247) optionally using arrow keys to expand and collapse a node.

**Comment by Alexander-Miller** [comment]
Since adding multiple roots will require a fairly large redesign anyway I've decided that it's the best point to break with backwards compatibility and old habits.

I'll be opening an issue on the spacemacs tracker some time soon, to introduce my ideas and get community feedback.
