### ISSUE TITLE
treemacs--post-command bug

### ISSUE THREAD

**Issue by basaran** [Alexander-Miller/treemacs#958]
Hello,

I use treemacs along with another package named `org-ol-tree` which under the hood is using treemacs. The post command hook defaulting to the user home folder has been causing all kind of weird rendering (I almost deleted my home directory once `[d]`) issues with treemacs, so I ended up shadowing it with the last line commented.

Perhaps, there would be another way to default it, like checking if it is actually treemacs itself somewhere. What do you think?

**Comment by Alexander-Miller** [comment]
I have some good news and some bad news:

The good news is that I will now start working on a fix.

The bad news is that I will soon publish a much-delayed (but quite necessary) overhaul of the extension api that will break everything. But it'll be asynchronous for better lsp integration, so that's something.
