### ISSUE TITLE
treemacs-git-modified-face not being applied

### ISSUE THREAD

**Issue by mattsawyer77** [Alexander-Miller/treemacs#980]
Hello, and thanks for this amazing package!

I noticed recently that git-modified files no longer seemed to be using `treemacs-git-modified-face` (which I had styled along with other treemacs faces to use a variable-width font).

When I described a character within the filename of a git-modified file, I saw the following text properties:

```
There are text properties here:
  :default-face        [Show]
  :depth               4
  :key                 [Show]
  :parent              [Show]
  :path                [Show]
  :state               file-node-closed
  button               (t)
  category             default-button
  face                 "M"
  help-echo            nil
  keymap               nil
```

For comparison, I described a character from within a git-unmodified file, and noticed that the `face` property is populated differently, instead of being set to "M" (which appears to be an undefined face?):

```
There are text properties here:
  :default-face        [Show]
  :depth               4
  :key                 [Show]
  :parent              [Show]
  :path                [Show]
  :state               file-node-closed
  button               (t)
  category             default-button
  face                 treemacs-git-unmodified-face
  help-echo            nil
  keymap               nil
```

I'm running emacs 28.2 GUI on macOS and I think I have the latest treemacs commit from master, but let me know if there is any other information I can provide or remedies to try.

**Comment by finex** [comment]
Hi, is this bug related to the fact that changed/untracked files does have a different font size? If so I'm also experiencing this bug using Doom Emacs + Treemacs.

**Comment by Alexander-Miller** [comment]
>   face                 "M"

That looks familiar. At least I remember fixing a bug where some code was not working right because a script would output faces instead of git's status indicators like "!", "?", "M". So best try again with the latest version of treemacs. Also restart Emacs so the caches are fresh and new scripts loaded.

If that doesn't help I need to know:
- what your git-mode, deferred or extended or ...?
- do you only see this when you edit a single file and treemacs auto-updates, or also when you refresh treemacs manually?

**Comment by mattsawyer77** [comment]
thanks @Alexander-Miller. I use Doom, which had treemacs pinned to 76807bef, so I was about 5 commits behind the latest. I unpinned it and updated it to 3b525ea26d2554ddffb11d1f44e0d76c11a1dde9. I checked my `+treemacs-git-mode`;  it was set to `'simple`. I restarted emacs, but the issue remained. I also tried changing the git mode to `'deferred`, and restarted emacs, but it didn't change anything. I'm happy to try any other changes or provide whatever info would be helpful.

**Comment by Alexander-Miller** [comment]
> I also tried changing the git mode to 'deferred, and restarted emacs, but it didn't change anything.

Did you just change the variable value? If so that won't work, you have to call the minor mode like this `(treemacs-git-mode 'deferred)`.

I am asking because the bug I remembered was also present in the `simple` git parsing code. 
That feature is neglected, but for a reason: I consider it an old stopgap made obsolete by first the  `extended` and then the `deferred` implementation. The simple mode gives you the worst of both words, it is both stupid and slow. 

I would hope the `simple` git-mode is not doom's default. Treemacs will to use `deferred` if it can, but you need a python3 binary that treemacs can find (see also `treemacs-python-executable`).

Anyway, I'll be pushing a fix for this soon, but I highly recommend you switch to a better git-mode version.

**Comment by mattsawyer77** [comment]
> Did you just change the variable value? If so that won't work, you have to call the minor mode like this (treemacs-git-mode 'deferred).

Indeed, I switched to using `(treemacs-git-mode 'deferred)` and this solved the issue even before I updated to the latest treemacs version. Thanks for the tip on treemacs-git-mode (I didn't know of it before).

I was thrown off a bit since, in doom emacs, there is a variable defined as `+treemacs-git-mode` that might attempt to manage this another way. But as you pointed out, simply setting that variable to `'deferred` had no effect. I'll look into filing a separate issue there.
