### ISSUE TITLE
Feature Request: Option to flatten empty directories

### ISSUE THREAD

**Issue by madhat2r** [Alexander-Miller/treemacs#996]
I often work in Clojure which organizes namespaces via directory structure so quite frequently there are a series of otherwise empty nested directories which are just namespace nesting like this
```
src
└── clojure
   └── realworld
      └── spec
         ├── core.clj
         └── interface.clj

```
It would be nice if `Treemacs`  could be configured to flatten it's display so that the top level would look more like this
```
src/clojure/realworld/spec
 ├── core.clj
 └── interface.clj

```
That way when navigating the directory tree you would only need to expand "one" folder to get to what you want.

**Comment by Alexander-Miller** [comment]
The feature you describe is treemacs' default behavior, and has been around for years now. Assuming you didn't set `treemacs-collapse-dirs` to 0 the issue is most likely that treemacs cannot find a valid python 3 binary on your computer. 

That python dependency is a hard requirement, no way around it. If you don't have it installed, then all you need is to install a reasonably up-to-date version of python, and treemacs will be able to detect it on the next start. If you do already have it, or if treemacs cannot find it for whatever reason, then you can still manually set `treemacs-python-executable` to the correct value.

**Comment by madhat2r** [comment]
I definitely missed that setting and apparently it was set to 0 by Doom.

Thanks for your help @Alexander-Miller, and sorry for the noise.
